### ISSUE TITLE
 Exception when canceling reaction creation. 

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#102]
I once had an issue with creating a reaction, but I could not reproduce it any more.

1) In a reactions-BB, select "Create new reaction".
2) Do not enter any name and press "ESC".
3)Object reference not set to an instance of an object.
Stack trace:

 at MoBi.Core.Commands.RemoveReactionBuilderCommand.RemoveFrom(IReactionBuilder reactionBuilderToRemove, IMoBiReactionBuildingBlock reactionBuildingBlock)
 at MoBi.Core.Commands.RemoveObjectBaseCommand`2.ExecuteWith(IMoBiContext context)
 at SBSuite.Core.Commands.SBSuiteCommand`1.Execute(TContext context)
 at BTS.Commands.MacroCommand`1.<>c__DisplayClass1.<Execute>b__0(ICommand`1 command)
 at BTS.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
 at BTS.Commands.MacroCommand`1.Execute(TExecutionContext context)
 at BTS.Commands.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
 at SBSuite.Core.Services.CommandTask.ResetChanges[TContext](ICommand`1 commandToReset, TContext context)
 at MoBi.Presentation.Tasks.Interaction.InteractionTaskContext.CancelCommand(IMoBiCommand command)
 at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.CancelCommand(IMoBiMacroCommand command)
 at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddNew(TParent parent, IBuildingBlock buildingBlockToAddTo)
 at MoBi.Presentation.UICommand.AddNewCommandFor`2.PerformExecute()
 at SBSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
 at SBSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)

4) An emtpy-named reactions symbol is created. Delete it
5)Object reference not set to an instance of an object.

Stack trace:

 at MoBi.Core.Commands.RemoveReactionBuilderCommand.RemoveFrom(IReactionBuilder reactionBuilderToRemove, IMoBiReactionBuildingBlock reactionBuildingBlock)
 at MoBi.Core.Commands.RemoveObjectBaseCommand`2.ExecuteWith(IMoBiContext context)
 at SBSuite.Core.Commands.SBSuiteCommand`1.Execute(TContext context)
 at BTS.Commands.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
 at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.RunRemoveCommand(TChild objectToRemove, TParent parent, IBuildingBlock buildingBlock)
 at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.Remove(TChild objectToRemove, TParent parent, IBuildingBlock buildingBlock, Boolean silent)
 at MoBi.Presentation.UICommand.RemoveCommandFor`2.Execute()
 at MoBi.Presentation.Presenter.ReactionDiagram.ReactionDiagramPresenter.RemoveReactionNode(ReactionNode reactionNode)
 at MoBi.Presentation.Presenter.ReactionDiagram.ReactionDiagramPresenter.removeItem(GoObject itemToDelete)
 at BTS.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
 at MoBi.Presentation.Presenter.ReactionDiagram.ReactionDiagramPresenter.RemoveSelection(IReadOnlyList`1 objectsToBeRemoved)
 at MoBi.UI.Views.ReactionDiagram.ReactionDiagramView.OnSelectionDeleting(CancelEventArgs e)
 at MoBi.UI.Views.BaseDiagram.MoBiBaseDiagramView.<>c__DisplayClass3_1.<InitializeResources>b__3()
 at BTS.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)

**Comment by msevestre** [comment]
This has probably been fixed with some changes in 7.0
