### ISSUE TITLE
Brand new project with simulation throws exception when reloaded

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1054]
```
Application:
MoBi® 12.0.0

Id OBUrmqLe6UeFhtFqcV8oLQ not unique

Stack trace:

at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlCacheSerializer`3.TypedDeserialize(ICache`2 cache, XElement cacheElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedDeserialize(TBuildingBlock bb, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement simulationElement, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Serializer\MoBiSimulationXmlSerializer.cs:line 35
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, MoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 122
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, MoBiProject project, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 94
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeContent[T](MetaDataContent content, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 165
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.addSimulationToProject(SimulationMetaData simulationMetaData, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 154
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 62
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 80
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Load(IMoBiContext context) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 56
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ContextPersistor.cs:line 93
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0() in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Tasks\SerializationTask.cs:line 56
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by rwmcintosh** [comment]
[test.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12161288/test.zip)
