### ISSUE TITLE
Deadlock when starting MoBi (11.2) via doubleclick on invalid simulation in Windows explorer

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1056]
[S1.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12194576/S1.zip)
When I open this file in MoBi, I get the error below (probably because it was saved in PK-Sim 12 - but that's another story).

<details><summary><b>Crash in MoBi 11.2</b></summary>
<p>

```
Application:
MoBi® 11.2.138

Object reference not set to an instance of an object.

Stack trace:

at MoBi.Core.Services.AmountToConcentrationConverter.Convert(Object objectToConvert)
   at MoBi.Core.Serialization.Services.PostSerializationStepsMaker.<PerformPostDeserializationFor>b__6_1[T](T o)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Core.Serialization.Services.PostSerializationStepsMaker.PerformPostDeserializationFor[T](IReadOnlyList`1 deserializedObjects, Int32 originalFileVersion, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.ProjectTask.loadSimulationTransferFromFileUsingDimensionMode(String fileName, ReactionDimensionMode dimensionMode)
   at MoBi.Presentation.Tasks.ProjectTask.LoadSimulationTransferDataFromFile(String fileName)
   at MoBi.Presentation.Tasks.ProjectTask.<>c__DisplayClass15_0.<loadSimulationFromFileInProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

</p>
</details> 

Now when I double click on this pkml file in Windows Explorer: MoBi 11.2 starts and hangs (need to kill per task manager then)

**Comment by PavelBal** [comment]
Cannot reproduce.
