### ISSUE TITLE
Exception when opening a project from PK-Sim

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1062]
Steps
1. Export a project from PK-Sim
2. Export
3. Open Simulation in MoBi
4. Save as a MoBi project
5. Open the project
6. Any operation on the simulation (like edit or even context menu)

```
Application:
MoBi® 12.0.0

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Id Zr10jdz9OEek1u7eph2aqw not unique

Stack trace:

at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at MoBi.Core.Domain.Services.RegisterTask.register(IWithId objectBase) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Domain\Services\RegisterTask.cs:line 36
   at MoBi.Core.Domain.Services.RegisterTask.Visit(IWithId objectBase) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Domain\Services\RegisterTask.cs:line 30
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Core.Domain.ObjectBase.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Module.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.ModuleConfiguration.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Builder.SimulationConfiguration.<>c__DisplayClass37_0.<AcceptVisitor>b__0(ModuleConfiguration x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Builder.SimulationConfiguration.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.ModelCoreSimulation.AcceptVisitor(IVisitor visitor)
   at MoBi.Core.Domain.Model.MoBiSimulation.AcceptVisitor(IVisitor visitor) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Domain\Model\MoBiSimulation.cs:line 139
   at MoBi.Core.Domain.Services.RegisterTask.RegisterAllIn(IWithId objectToRegister) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Domain\Services\RegisterTask.cs:line 54
   at MoBi.Core.Domain.Model.MoBiContext.Register(IWithId objectBase) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Domain\Model\MoBiContext.cs:line 183
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuForSimulation.InitializeWith(ObjectBaseDTO dto, IPresenter presenter) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForSimulation.cs:line 39
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuSpecificationFactoryForSimulation.CreateFor(IViewItem viewItem, IPresenterWithContextMenu`1 presenter) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForSimulation.cs:line 218
   at OSPSuite.Presentation.Presenters.ContextMenus.ContextMenuFactory`1.CreateFor(TObjectRequestingContextMenu objectRequestingContextMenu, IPresenterWithContextMenu`1 presenter)
   at MoBi.Presentation.Presenter.Main.ExplorerPresenter`2.ContextMenuFor(IViewItem viewItem) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Presenter\Main\ExplorerPresenter.cs:line 92
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.ContextMenuFor(ITreeNode treeNode) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Presenter\Main\SimulationExplorerPresenter.cs:line 162
   at MoBi.Presentation.Presenter.Main.ExplorerPresenter`2.ShowContextMenu(ITreeNode treeNode, Point popupLocation) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Presenter\Main\ExplorerPresenter.cs:line 69
   at OSPSuite.Presentation.Extensions.PresenterWithContextMenuExpression`1.<>c__DisplayClass3_0.<At>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by rwmcintosh** [comment]
The issue this time is the Module id

**Comment by msevestre** [comment]
Look like we are NOT UNREGISTERING module when we close a project?

**Comment by rwmcintosh** [comment]
we aren't cloning modules or bb's when importing

**Comment by rwmcintosh** [comment]
> but if you open the project, it should not be there already right?

The project building block Id and the simulation building block Id are the same when I re-open after saving.

Very likely there are two problems, the one I mentioned, and - we don't register the cloned building blocks or module when importing.
