### ISSUE TITLE
Cannot open a v11.2 project in v12

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1073]
https://github.com/Open-Systems-Pharmacology/OSMOSES/blob/examples/UseCases/V11.2/omeprazole%2040mg%20po%20asian%20EM%20fluvoxamine%2050mg%20po_V11.mbp3

- A v11.2 snapshot has been loaded in PK-Sim v11.2
- A simulation has been saves a pkml
- The pkml simulation has been opened with MoBi v11.2 and the project has been saved
- Loading the project with MoBi V12:

Application:
MoBi® 12.0.43

Sequence contains no matching element

Stack trace:
```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MoBi.Core.Services.TemplateResolverTask.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.TemplateBuildingBlockFor(IBuildingBlock buildingBlock)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.<findChangedTemplateBuildingBlocks>b__22_0(IBuildingBlock x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.refreshDisplayedSimulation(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToTree(ITreeNode`1 classificationNode, ClassifiableSimulation classifiableSimulation)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.AddClassifiableToTree[T](T classifiable, RootNodeType rootNodeType, Func`3 addClassifiableToTree)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToSimulationRootFolder(ClassifiableSimulation classifiableSimulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.<AddProjectToTree>b__3_0(ClassifiableSimulation x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.AddProjectToTree(MoBiProject project)
   at MoBi.Presentation.Presenter.Main.ExplorerPresenter`2.AddProjectToTree(IProject project)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.Handle(ProjectCreatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by PavelBal** [comment]
This does not happen when opening the v11.2 pkml directly in v12.

**Comment by rwmcintosh** [comment]
During project conversion, a new module is introduced. This particular scenario is straightforward: all the building blocks come from one simulation, and they all share the name of the simulation; the module should also be that name.

But in the case of general MoBi 11 project conversion, we need a way to name newly introduced modules.

This has to fit with our convention that simulation building blocks match with project building blocks by both the building block name and the module name. In other words, the simulation's module and building block name must match the module and building block name in the project.

**Comment by rwmcintosh** [comment]
Here's a project with module/building block implemented. I need the building block type as part of the module name to prevent naming collisions

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/30d144f4-e171-41f4-aa00-65e855e5bef5)

For now, let's keep it simple and make this the only conversion. I think the only other scenario is not whether the building blocks fit in one module, but whether or not there is only one simulation. If only one simulation, we might consider grouping the building blocks into one module.

**Comment by PavelBal** [comment]
Damn this is ugly :D But let's keept it like this.

**Comment by rwmcintosh** [comment]
I removed the conditional module tree creation where you only see the IC/PV folders when there's multiple BB's to group. This view makes me think we might need that.

It was removed because creating the tree view differently for different configurations might be confusing for users, but IDK if that's worse or if this is worse.

**Comment by msevestre** [comment]
should we remove IC and PV for converted modules? e.g.

**Comment by PavelBal** [comment]
> should we remove IC and PV for converted modules? e.g.

If they are empty - yes.

**Comment by rwmcintosh** [comment]
Maybe it won't hurt to remove the folder node if there is only a single building block that would be contained in it. What do you guys think? We had that before but removed it.

We could do that in general, or only in the case of single building block modules. Thoughts?

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/0f719194-9e00-4b03-a1ee-4fcc48f86440)

**Comment by rwmcintosh** [comment]
We will leave the folders because there is a context menu associated with them. When we remove the folders, there's still a way to add PV or IC from the module context menu.
