### ISSUE TITLE
Error when trying to load a Simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1087]
[Modules.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12454881/Modules.zip)

1. Open simulation "Core_GHM.pkml"
2. Try to add the simulation "C-Peptide.pkml"

Application:
MoBi® 12.0.46

Sequence contains more than one matching element

Stack trace:
```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MoBi.Core.Services.TemplateResolverTask.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.TemplateBuildingBlockFor(IBuildingBlock buildingBlock)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.<findChangedTemplateBuildingBlocks>b__22_0(IBuildingBlock x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.refreshDisplayedSimulation(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToTree(ITreeNode`1 classificationNode, ClassifiableSimulation classifiableSimulation)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.AddClassifiableToTree[T](T classifiable, RootNodeType rootNodeType, Func`3 addClassifiableToTree)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToSimulationRootFolder(ClassifiableSimulation classifiableSimulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.<AddProjectToTree>b__3_0(ClassifiableSimulation x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.AddProjectToTree(MoBiProject project)
   at MoBi.Presentation.Presenter.Main.ExplorerPresenter`2.AddProjectToTree(IProject project)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.Handle(ProjectCreatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by PavelBal** [comment]
OK this seems only to happen when I try https://github.com/Open-Systems-Pharmacology/MoBi/issues/1086 first

**Comment by rwmcintosh** [comment]
This raises a legitimate question what to do when importing simulations. MoBi wants to create a module in the project that contains all the building blocks of the simulation. It's necessary for the name of the module in the project to match the name of the module in the simulation. This is how we relate them during update/commit.

In this case, if I export the C-Peptide module on its own, then I open the Core_GHM.pkml simulation, load the C-Peptide module, then try to load the C-Peptide simulation, this exception will be thrown.

**Comment by rwmcintosh** [comment]
To solve this particular case we need to make sure that if  simulation is opened and a new module is created from it, then the new module should be uniquely named in the project (and the simulation module name has to follow that unique name).

**Comment by Yuri05** [comment]
> 1. Open simulation "Core_GHM.pkml"

When trying to open this simulation now I got a crash. But because it was created with some intermediate version of MoBi - not sure if we have here a problem

@PavelBal @rwmcintosh
