### ISSUE TITLE
V12: Error displaying ontogeny formula in individual

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1129]
When clicking on one of the highlighted formulas
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/bf4897b3-3a90-49e6-b212-521c540507bb)

I get the error
```
Application:
MoBi® 12.0.0

Formula 'DistributedTableFormula' not supported at the moment

Stack trace:

at MoBi.Presentation.Presenter.FormulaPresenterCache.PresenterFor(Type formulaType) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\FormulaPresenterCache.cs:line 60
   at MoBi.Presentation.Presenter.FormulaPresenterCache.PresenterFor(IFormula formula) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\FormulaPresenterCache.cs:line 33
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Select(IFormula formula) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\FormulaCachePresenter.cs:line 166
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Select(FormulaBuilderDTO formulaDTO) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\FormulaCachePresenter.cs:line 100
   at MoBi.UI.Views.FormulaCacheView.<>c__DisplayClass4_1.<InitializeBinding>b__7() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.UI\Views\FormulaCacheView.cs:line 54
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
Fixed
