### ISSUE TITLE
Error when loading an exported organ in a new module

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1177]
1. Import a PBPK model into MoBi (v12)
2. Open the SS-BB and save the the organ "Muscle" via "Save With Individual..."
3. Create a new module "Tumor"
4. Try to load the exported organ in the SS-BB of the module "Tumor":

Application:
MoBi® 12.0.90

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Mappers.ObjectBaseToObjectBaseDTOMapperBase.MapProperties(IObjectBase objectBase, ObjectBaseDTO objectBaseDTO)
   at MoBi.Presentation.Mappers.ObjectBaseToObjectBaseDTOMapperBase.Map[T](T dto)
   at MoBi.Presentation.Mappers.ObjectBaseToObjectBaseDTOMapper.MapFrom(IObjectBase objectBase)
   at MoBi.Presentation.Presenter.HierarchicalSpatialStructurePresenter.Handle(AddedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by rwmcintosh** [comment]
It even happens when you try adding a new top container to an empty spatial structure.
