### ISSUE TITLE
Exported organism using Save with Individual context menu

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1222]
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/17ea51a6-ceef-49ad-ae9b-afb998a0adca)

**Comment by PavelBal** [comment]
Application:
MoBi® 12.0.115

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Core.Domain.ObjectBaseExtensions.Find[T](IEnumerable`1 enumerable, Func`2 predicate)
   at OSPSuite.Core.Domain.ObjectBaseExtensions.FindByName[T](IEnumerable`1 enumerable, String objectName)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.addIndividualParameterToContainer(IndividualParameter individualParameter, IContainer container, String containerPath)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.<>c__DisplayClass11_0.<addIndividualParametersToContainer>b__4(IndividualParameter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.addIndividualParametersToContainer(IndividualBuildingBlock individual, IContainer container, ObjectPath containerPath)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.<>c__DisplayClass10_0.<addIndividualParametersToContainers>b__0(IContainer subContainer)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.addIndividualParametersToContainers(IndividualBuildingBlock individual, IContainer container)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.exportContainer(IContainer container, String fileName, IndividualBuildingBlock individual)
   at MoBi.Presentation.Tasks.Edit.EditTaskForContainer.SaveWithIndividual(IContainer container)
   at MoBi.Presentation.UICommand.SaveWithIndividualUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
This happens when exporting the top level container
