### ISSUE TITLE
V12: Crash when undoing "Remove output interval"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1227]
This worked in V11.2 but crashes in V12. E.g. 
* open the project attached [12.0_NegApp.mbp3.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/13511858/12.0_NegApp.mbp3.zip)
* remove the 2nd output interval in the simulation
<details><summary>Screen</summary>

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/6d8464a7-9855-4efa-9cd8-07570c9e14be)
</details> 

* Click on "Undo" in the history

```
Application:
MoBi® 12.0.0

Object reference not set to an instance of an object.

Stack trace:

at MoBi.Core.Commands.OutputIntervalCommandBase.RestoreExecutionData(IMoBiContext context) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Commands\AddOutputIntervalCommand.cs:line 25
   at OSPSuite.Core.Commands.Core.RollBackCommand`1.<>c__DisplayClass3_0.<Execute>b__0(IReversibleCommand`1 command)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Commands.Core.RollBackCommand`1.Execute(TExecutionContext context)
   at OSPSuite.Core.Commands.Core.HistoryManager`1.RollBackTo(Int32 state)
```

**Comment by Yuri05** [comment]
EDIT: in 11.2 it did not work (the removed output interval was not restored) - it just did not crash :)
