### ISSUE TITLE
Cannot export ODE system in 7.1

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#123]
Following error occurs when trying to export the ODE system to matlab (via right click on simulation, and selecting "Export Simulation to Matlab Differential Equations")

""
Could not load file or assembly 'Microsoft.WindowsAPICodePack, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Das System kann die angegebene Datei nicht finden.

at OSPSuite.UI.Services.DialogCreator.AskForFolder(String title, String directoryKey, String defaultDirectory)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.AskForFolder(String title, String directoryKey)
   at MoBi.Presentation.Tasks.Edit.EditTasksForSimulation.ExportMatlabDifferentialSystem(IMoBiSimulation simulation)
   at MoBi.Presentation.UICommand.ExportMatlabODEUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
""

[MoBi Error Export ODE.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1111780/MoBi.Error.Export.ODE.zip)

**Comment by msevestre** [comment]
Let's fixed that for 7.2. This is probably a straight forward dependency missing in setup.

**Comment by PavelBal** [comment]
Same error for exporting a PI to matlab...

**Comment by msevestre** [comment]
yes this is fixed in 7.2
If you need this feature absolutely, you can do the following
1. Close MoBi
1. Go to your PKSim Install Folder e.g. _C:\Program File....\Open Systems Pharmacology\PK-Sim\7.1_
1. Copy the dlls `Microsoft.WindowsAPICodePack.dll` and `Microsoft.WindowsAPICodePack.Shell.dll`
1. Paste those dlls in your MoBi folder e.g. _C:\Program File....\Open Systems Pharmacology\MoBi\7.1_

**Comment by PavelBal** [comment]
Thanks.
