### ISSUE TITLE
V12: Explicit error message if wrong PK-Sim version is registered

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1254]
In my MoBi 12, PK-Sim 11 was wrongly registered under options:
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/d9bea566-a746-4080-adce-2e038d5d98c9)

When trying to create an individual, the error message below comes.
Would be better to have an explicit message (e.g. "wrong PK-Sim version")

```
Application:
MoBi® 12.0.0

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Method not found: 'OSPSuite.Core.Domain.ObjectPath OSPSuite.Core.Domain.IObjectPathFactory.CreateObjectPathFrom(System.String[])'.

Stack trace:

at PKSim.Infrastructure.ORM.Mappers.FlatRelativeObjectPathToObjectPathMapper.MapFrom(Int64 flatObjectPathId)
   at PKSim.Infrastructure.ORM.Mappers.FlatObjectPathToObjectPathMapper.MapFrom(FlatObjectPath flatObjectPath) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\ORM\Mappers\FlatObjectPathToObjectPathMapper.cs:line 34
   at PKSim.Infrastructure.ORM.Mappers.FlatRateObjectToFormulaUsablePathMapper.MapFrom(FlatRateObjectPath flatRateObjectPath) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\ORM\Mappers\FlatRateObjectPathsToObjectPathsMapper.cs:line 30
   at PKSim.Infrastructure.ORM.Repositories.RateObjectPathsRepository.DoStart() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\ORM\Repositories\RateObjectPathsRepository.cs:line 52
   at OSPSuite.Utility.Collections.StartableRepository`1.Start()
   at PKSim.Infrastructure.ORM.Repositories.RateObjectPathsRepository.ObjectPathsFor(RateKey rateKey) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\ORM\Repositories\RateObjectPathsRepository.cs:line 76
   at PKSim.Core.Model.FormulaFactory.createFormula(RateKey rateKey) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\FormulaFactory.cs:line 339
   at PKSim.Core.Model.FormulaFactory.RateFor(RateKey rateKey, IFormulaCache formulaCache) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\FormulaFactory.cs:line 250
   at PKSim.Core.Model.FormulaFactory.RateFor(String calculationMethod, String rate, IFormulaCache formulaCache) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\FormulaFactory.cs:line 288
   at PKSim.Core.Model.FormulaFactory.RateFor(ParameterRateMetaData rateDefinition, IFormulaCache formulaCache) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\FormulaFactory.cs:line 146
   at PKSim.Core.Model.ParameterFactory.CreateFor(ParameterRateMetaData parameterRateDefinition, IFormulaCache formulaCache) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\ParameterFactory.cs:line 95
   at PKSim.Core.Services.ParameterContainerTask.addParametersTo(IContainer parameterContainer, OriginData originData, IEnumerable`1 calculationMethods, Func`2 predicate, Action`2 parameterValueModifier, IFormulaCache formulaCache) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\ParameterContainerTask.cs:line 191
   at PKSim.Core.Services.ParameterContainerTask.AddIndividualParametersTo[TContainer](TContainer parameterContainer, OriginData originData) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\ParameterContainerTask.cs:line 54
   at PKSim.Core.Services.IndividualModelTask.addModelStructureTo(IContainer container, OriginData originData, Boolean addParameter) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\IndividualModelTask.cs:line 166
   at PKSim.Core.Services.IndividualModelTask.CreateModelFor(Individual individual) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\IndividualModelTask.cs:line 65
   at PKSim.Core.Model.IndividualFactory.createStandardIndividual(OriginData originData, Func`2 createAction) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\IndividualFactory.cs:line 107
   at PKSim.Core.Model.IndividualFactory.CreateStandardFor(OriginData originData) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\IndividualFactory.cs:line 76
   at PKSim.Core.Services.DefaultIndividualRetriever.DefaultIndividualFor(SpeciesPopulation speciesPopulation) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DefaultIndividualRetriever.cs:line 61
   at PKSim.Core.Services.DefaultIndividualRetriever.DefaultIndividualFor(Species species) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DefaultIndividualRetriever.cs:line 40
   at PKSim.Core.Services.DefaultIndividualRetriever.DefaultIndividual() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DefaultIndividualRetriever.cs:line 30
   at PKSim.Presentation.Presenters.Individuals.IndividualSettingsPresenter.PrepareForCreating() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Individuals\IndividualSettingsPresenter.cs:line 123
   at PKSim.Presentation.Presenters.Individuals.AbstractCreateIndividualPresenter.Create() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Individuals\CreateIndividualPresenter.cs:line 45
   at PKSim.UI.Starter.IndividualCreator.CreateIndividual() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.UI.Starter\IndividualCreator.cs:line 21
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MoBi.Presentation.Tasks.PKSimStarter.executeMethod(MethodInfo method, Object[] parameters) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\PKSimStarter.cs:line 94
   at MoBi.Presentation.Tasks.PKSimStarter.executeAndCloneBuildingBlock[TBuildingBlock](MethodInfo method) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\PKSimStarter.cs:line 77
   at MoBi.Presentation.Tasks.PKSimStarter.CreateIndividual() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\PKSimStarter.cs:line 71
   at MoBi.Presentation.UICommand.AddNewIndividualCommand.createBuildingBlockFromPKSim() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\UICommand\AddNewIndividualCommand.cs:line 17
   at MoBi.Presentation.UICommand.AddNewFromPKSimCommand`1.PerformExecute() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\UICommand\AddNewBuildingBlockCommand.cs:line 25
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
![image](https://github.com/user-attachments/assets/91c32b8b-1b4f-432b-bbf9-109abeb3e624)
