### ISSUE TITLE
Can't save the model without downloading the latest version of mobi?

### ISSUE THREAD

**Issue by D7abc** [Open-Systems-Pharmacology/MoBi#1263]
I didn't download the latest version, just opened MOBI from the file（As shown in the figure below）, imported the model in the new version and made modifications, and finally couldn't save it. What should I do? I downloaded an old version and didn't want to update it because there was a model that had already been built. But I really need the model in the new version.
![YYYUAT@791 72N9C9MU$RD2](https://github.com/Open-Systems-Pharmacology/MoBi/assets/141010984/fa97e81a-7631-4aa2-92c5-9d8420cc9802)

The problem shows:Application:
MoBi® 11.0.126

could not execute query
[ SELECT this_.Id as id1_7_2_, this_.Version as version2_7_2_, this_.ContentId as contentid3_7_2_, children2_.ProjectId as projectid4_3_4_, children2_.Id as id1_3_4_, children2_.Id as id1_3_0_, children2_.Discriminator as discriminator2_3_0_, children2_.ContentId as contentid3_3_0_, case when children2_1_.SimulationId is not null then 1 when children2_.Id is not null then 0 end as clazz_0_, historical3_.SimulationId as simulationid3_2_5_, historical3_.Id as id1_2_5_, historical3_.Id as id1_2_1_, historical3_.ContentId as contentid2_2_1_ FROM PROJECTS this_ left outer join ENTITIES children2_ on this_.Id=children2_.ProjectId left outer join SIMULATIONS children2_1_ on children2_.Id=children2_1_.SimulationId left outer join DATA_REPOSITORIES historical3_ on children2_.Id=historical3_.SimulationId ]
[SQL: SELECT this_.Id as id1_7_2_, this_.Version as version2_7_2_, this_.ContentId as contentid3_7_2_, children2_.ProjectId as projectid4_3_4_, children2_.Id as id1_3_4_, children2_.Id as id1_3_0_, children2_.Discriminator as discriminator2_3_0_, children2_.ContentId as contentid3_3_0_, case when children2_1_.SimulationId is not null then 1 when children2_.Id is not null then 0 end as clazz_0_, historical3_.SimulationId as simulationid3_2_5_, historical3_.Id as id1_2_5_, historical3_.Id as id1_2_1_, historical3_.ContentId as contentid2_2_1_ FROM PROJECTS this_ left outer join ENTITIES children2_ on this_.Id=children2_.ProjectId left outer join SIMULATIONS children2_1_ on children2_.Id=children2_1_.SimulationId left outer join DATA_REPOSITORIES historical3_ on children2_.Id=historical3_.SimulationId]
-----------------------------------------------------
SQL logic error
no such table: PROJECTS

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFromDatabase()
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Save(IMoBiProject project, IMoBiContext context)
   at MoBi.Core.Serialization.ORM.ContextPersistor.Save(IMoBiContext context)
   at MoBi.Presentation.Tasks.SerializationTask.SaveProject()
   at MoBi.Presentation.Tasks.ProjectTask.saveProject()
   at MoBi.Presentation.Tasks.ProjectTask.Save()
   at MoBi.Presentation.UICommand.SaveProjectCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
If you need several versions of MoBi in parallel on your computer, use portable versions.
* Go to https://github.com/Open-Systems-Pharmacology/MoBi/releases 
* Navigate to your release of interest
* Download and unzip **mobi-portable-setup.zip** from this release

**Comment by D7abc** [comment]
But I can't save the model I built in the end, what should I do?
![3NND~T37}2L4`_H8Q3%16ZP](https://github.com/Open-Systems-Pharmacology/MoBi/assets/141010984/d07f8a45-e71d-4e49-a8c5-5afef135f76c)

**Comment by D7abc** [comment]
thanks a lot!!
