### ISSUE TITLE
Error in adding a parameter

### ISSUE THREAD

**Issue by miao-chan** [Open-Systems-Pharmacology/MoBi#1274]
The version I am using is V11. The error message window pops out (see picture below) whenever I try to add a parameter in the building blocks, no matter if the parameter is added in the 'Molecules' or 'Reactions' building block. In addition, this issue happened not only in the simulation I exported from PK-Sim (V11) but also in the MoBi file downloaded from [OSP forum](https://github.com/Open-Systems-Pharmacology/Forum/discussions/770). 

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/131871579/6cf0ef84-f2f3-4279-aebd-01f6b0ac27ec)

Here is the information copied from the error message window.
Application:
MoBi® 11.0.138

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Mappers.ParameterToParameterDTOMapper.MapFrom(IParameter parameter)
   at MoBi.Presentation.Presenter.EditParameterPresenter.Edit(IParameter parameter, IEnumerable`1 existingObjectsInParent)
   at MoBi.Presentation.Tasks.Edit.EditTaskFor`1.EditEntityModal(T entity, IEnumerable`1 existingObjectsInParent, ICommandCollector commandCollector, IBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddNew(TParent parent, IBuildingBlock buildingBlockToAddTo)
   at MoBi.Presentation.Presenter.EditParametersInContainerPresenter.AddParameter()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by AoleZheng** [comment]
Hello Chan! I met the same problem recently. I wonder know did you fix this problem? I tried to update the version of PKsim and Mobi. But it still didn't work. 
![image](https://github.com/user-attachments/assets/69c238ac-8127-43f2-ac1b-3e00a32ba35a)
My version is Mobi 11.3, but the problem also happened in v11.2

Application:
MoBi® 11.3.207

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Mappers.ParameterToParameterDTOMapper.MapFrom(IParameter parameter)
   at MoBi.Presentation.Presenter.EditParameterPresenter.Edit(IParameter parameter, IEnumerable`1 existingObjectsInParent)
   at MoBi.Presentation.Tasks.Edit.EditTaskFor`1.EditEntityModal(T entity, IEnumerable`1 existingObjectsInParent, ICommandCollector commandCollector, IBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddNew(TParent parent, IBuildingBlock buildingBlockToAddTo)
   at MoBi.Presentation.Presenter.EditParametersInContainerPresenter.AddParameter()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
Which operating system are you using?
Which language (regional) settings are you using?

**Comment by AoleZheng** [comment]
> Which operating system are you using? Which language (regional) settings are you using?

I use the win11 system. And my system language is Chinese, my Mobi language setting is English. My colleague uses the same settings as me. She can add parameters successfully. Could there be any problem with my computer environment?

Thanks for your kind help!

**Comment by miao-chan** [comment]
> Which operating system are you using? Which language (regional) settings are you using?

Hi Yuri05,

I am using Win11 with a 64-bit operating system, and the system and software language are English.
This problem was temporarily solved by deleting the roaming data folder. Afterward, I can create new parameters without the system crashing.

Kind regards,
Miao-Chan

**Comment by rwmcintosh** [comment]
> > Which operating system are you using? Which language (regional) settings are you using?
> 
> Hi Yuri05,
> 
> I am using Win11 with a 64-bit operating system, and the system and software language are English. This problem was temporarily solved by deleting the roaming data folder. Afterward, I can create new parameters without the system crashing.
> 
> Kind regards, Miao-Chan

Thanks for this update. It was critical to finding the cause.
