### ISSUE TITLE
Error in Simulation creation Wizard

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1297]
When in Simulation creation Wizard I click on selected proteins, I get from time to time the error message below.
Not fully reproducible (e.g. in the screen below I just keep clicking on proteins 1, 2, 3 in some arbitrary order and after a while I get it)

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/74eeb125-31b4-4368-bef3-01b974866ee6)

```
Application:
MoBi® 12.0.0

Index must be within the bounds of the List.
Parameter name: index

Stack trace:

at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at MoBi.Presentation.Presenter.EditIndividualAndExpressionConfigurationsPresenter.MoveNode(ITreeNode dragNode, ITreeNode targetNode) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\EditIndividualAndExpressionConfigurationsPresenter.cs:line 168
   at OSPSuite.UI.Binders.TreeNodeExplorerViewDragDropBinder.<>c__DisplayClass6_0.<treeViewDragDrop>b__0(ITreeNode node)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Binders.TreeNodeExplorerViewDragDropBinder.treeViewDragDrop(DragEventArgs e)
   at OSPSuite.UI.Binders.TreeNodeExplorerViewDragDropBinder.<>c__DisplayClass18_0`1.<onEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
Not reproducible.
