### ISSUE TITLE
Renaming a module should not trigger "Rename related entities"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1343]
I have a module called "Lysosome". Within this module, there is a container "Lysosome" and some entries in the IC and PV BBs that contain the part "Lysosome." When trying to rename the module, the dialog "Rename related entities" that suggests to rename the container and the entries within the IC and PV BBs.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/9a4f32dc-ead1-414d-bcdf-c10a94d3bf9c)

I think this should not be the case. In 99% of cases, it is not desirable and may lead to errors.

**Comment by benjaperez1983** [comment]
Found a bug trying to reproduce this functionality.
Thought it might be related with some changes we introduced but seems to be on develop branch without our changes.
I will solve this issue as well on this Ticket if @PavelBal  and @rwmcintosh  agree.

The bug:

Create a top container:
![image](https://github.com/user-attachments/assets/19d2fd68-8fd7-4c0a-818e-91daf1426ee4)

Give it a name (optional) and click select parent path:
![image](https://github.com/user-attachments/assets/de6a04c2-abe2-471d-afad-85c2c47c4779)

Select "Main Module" -> selected by default and click ok:
![image](https://github.com/user-attachments/assets/098e22e7-8831-4da9-a095-912fb73731b3)

![image](https://github.com/user-attachments/assets/4a274582-6dd3-45f6-b91c-22bd2335f009)


![image](https://github.com/user-attachments/assets/8e6ae9f9-3ce3-40dd-919c-644b36ef5a4e)


The stackTrace:
at OSPSuite.Core.Domain.ObjectPathFactory.addPathEntry(IEntity entity, ObjectPath objectPath)
   at OSPSuite.Core.Domain.ObjectPathFactory.CreateAbsoluteObjectPath(IEntity entity)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForTopContainer.BuildObjectPath(IContainer container) in C:\Users\BenjaminMarianoPerez\source\repos\MoBi\src\MoBi.Presentation\Tasks\Interaction\InteractionTasksForTopContainer.cs:line 48
   at MoBi.Presentation.Presenter.SelectContainerInTreePresenter.get_SelectedEntityPath() in C:\Users\BenjaminMarianoPerez\source\repos\MoBi\src\MoBi.Presentation\Presenter\SelectContanerInTreePresenter.cs:line 36
   at MoBi.Presentation.Presenter.SelectContainerPresenter.Select(ObjectPath excludedObjectPath) in C:\Users\BenjaminMarianoPerez\source\repos\MoBi\src\MoBi.Presentation\Presenter\SelectContainerPresenter.cs:line 47
   at MoBi.Presentation.Presenter.EditContainerPresenter.UpdateParentPath() in C:\Users\BenjaminMarianoPerez\source\repos\MoBi\src\MoBi.Presentation\Presenter\EditContainerPresenter.cs:line 72
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)

**Comment by rwmcintosh** [comment]
> Found a bug trying to reproduce this functionality. Thought it might be related with some changes we introduced but seems to be on develop branch without our changes. I will solve this issue as well on this Ticket if @PavelBal and @rwmcintosh agree.

since the PR is in, can you create another issue for this with the same details you provided here.

**Comment by benjaperez1983** [comment]
This issue is closed allong with #1432 Rename from context menu
