### ISSUE TITLE
Cannot load a spatial structures BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1376]
From the same project as in https://github.com/Open-Systems-Pharmacology/MoBi/issues/1354

1. Save the spatial structure as PKML
2. Create a new module and try to load it as PKML:

Application:
MoBi® 12.0.263

Unable to find a serializer for 'OSPSuite.Core.Domain.Builder.SpatialStructure'

Stack trace:
```
at OSPSuite.Serializer.Xml.XmlSerializerRepository`1.SerializerFor(Type typeOfObjectToSerialize)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.serializeFor(Type type)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.ElementNameFor(Type type)
   at MoBi.Presentation.Tasks.SerializationTask.retrieveElementsToDeserializeFromFile[T](XElement xelRoot, String fileName)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.loadBuildingBlock(BuildingBlockType buildingBlockType, String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.loadBuildingBlocksToModule(Module module, Func`1 getFilename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.LoadBuildingBlocksToModule(Module module)
   at MoBi.Presentation.UICommand.LoadBuildingBlocksToModuleUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Also reactions:

Application:
MoBi® 12.0.263

Unable to find a serializer for 'OSPSuite.Core.Domain.Builder.ReactionBuildingBlock'

Stack trace:
```
at OSPSuite.Serializer.Xml.XmlSerializerRepository`1.SerializerFor(Type typeOfObjectToSerialize)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.serializeFor(Type type)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.ElementNameFor(Type type)
   at MoBi.Presentation.Tasks.SerializationTask.retrieveElementsToDeserializeFromFile[T](XElement xelRoot, String fileName)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.loadBuildingBlock(BuildingBlockType buildingBlockType, String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.loadBuildingBlocksToModule(Module module, Func`1 getFilename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForModule.LoadBuildingBlocksToModule(Module module)
   at MoBi.Presentation.UICommand.LoadBuildingBlocksToModuleUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
