### ISSUE TITLE
Exception when creating new table formula

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#139]
1. Open NewPassiveTransportBB under Passive Transports
1. On Kinetic of NewPassiveTransport select NewTableFormula if not already selected
1. Use ellipsis buttons to try to select 'Path to table object'

Exception trace

```
Application:
MoBi 7.2.0 - Build 0

Object reference not set to an instance of an object.

Stack trace:
at MoBi.Presentation.Presenter.SelectReferencePresenterFactory.ReferenceAtParameterFor(IContainer container) in C:\git\MoBi\src\MoBi.Presentation\Presenter\SelectReferencePresenterFactory.cs:line 25
   at MoBi.Presentation.Presenter.EditTableFormulaWithOffSetFormulaPresenter.selectFormulaUseablePath(FormulaUsablePathDTO initPath, Func`2 predicate, String caption) in C:\git\MoBi\src\MoBi.Presentation\Presenter\EditTableFormulaWithOffSetFormulaPresenter.cs:line 86
   at MoBi.Presentation.Presenter.EditTableFormulaWithOffSetFormulaPresenter.SetTableObjectPath(FormulaUsablePathDTO formulaUsablePath) in C:\git\MoBi\src\MoBi.Presentation\Presenter\EditTableFormulaWithOffSetFormulaPresenter.cs:line 69
   at MoBi.UI.Views.EditTableFormulaWithOffSetFormulaView.btEditTableObjectPathOnButtonClick() in C:\git\MoBi\src\MoBi.UI\Views\EditTableFormulaWithOffSetFormulaView.cs:line 50
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0() in C:\projects\ospsuite-core\src\OSPSuite.UI\Controls\BaseUserControl.cs:line 112
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Extensions\ExceptionExtensions.cs:line 16
```

**Comment by rwmcintosh** [comment]
[TableFormulaException.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1125740/TableFormulaException.zip)

**Comment by msevestre** [comment]
same with path of offset object.

**Comment by msevestre** [comment]
to be honest, table formula with offset seems to not make sense at all here. That should not crash anyways

**Comment by StephanSchaller** [comment]
Hmm, I just tried this in 7.3.0 and got and Error:

Application:
MoBi 7.3.0.35

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.SelectReferencePresenterFactory.ReferenceAtParameterFor(IContainer container)
   at MoBi.Presentation.Presenter.EditTableFormulaWithOffsetFormulaPresenter.selectFormulaUseablePath(Func`2 predicate, String caption)
   at MoBi.Presentation.Presenter.EditTableFormulaWithOffsetFormulaPresenter.SetTableObjectPath()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
