### ISSUE TITLE
 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#145]
After creating a reaction, adding some parameters, changing values etc, I got the following exception
Not sure of the workflow and could not reproduce it...but it's there

Application:
MoBi 7.2.0 - Build 0

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Core.Commands.SetConstantFormulaValueCommand..ctor(ConstantFormula constantFormula, Double newValue, Unit displayUnit, Unit oldUnit, IBuildingBlock buildingBlock, IEntity formulaOwner) in C:\projects\MoBi\src\MoBi.Core\Commands\SetConstantFormulaValueCommand.cs:line 36
   at MoBi.Core.Commands.SetConstantFormulaValueCommand.GetInverseCommand(IMoBiContext context) in C:\projects\MoBi\src\MoBi.Core\Commands\SetConstantFormulaValueCommand.cs:line 48
   at OSPSuite.Core.Commands.OSPSuiteReversibleCommand`1.InverseCommand(TContext context) in C:\projects\ospsuite-core\src\OSPSuite.Core\Commands\OSPSuiteCommand.cs:line 56
   at OSPSuite.Core.Commands.Core.MacroCommand`1.InverseCommand(TExecutionContext context) in C:\projects\ospsuite-core\src\OSPSuite.Core\Commands\Core\MacroCommand.cs:line 100
   at OSPSuite.Core.Commands.Core.MacroCommand`1.InverseCommand(TExecutionContext context) in C:\projects\ospsuite-core\src\OSPSuite.Core\Commands\Core\MacroCommand.cs:line 100
   at OSPSuite.Core.Services.CommandTask.ResetChanges[TContext](ICommand`1 commandToReset, TContext context) in C:\projects\ospsuite-core\src\OSPSuite.Core\Services\CommandTask.cs:line 18
   at MoBi.Presentation.Tasks.Interaction.InteractionTaskContext.CancelCommand(IMoBiCommand command) in C:\projects\MoBi\src\MoBi.Presentation\Tasks\Interaction\InteractionTaskContext.cs:line 100
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.CancelCommand(IMoBiMacroCommand command) in C:\projects\MoBi\src\MoBi.Presentation\Tasks\Interaction\InteractionTaskFor.cs:line 127
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddNew(TParent parent, IBuildingBlock buildingBlockToAddTo) in C:\projects\MoBi\src\MoBi.Presentation\Tasks\Interaction\InteractionTaskFor.cs:line 77
   at MoBi.Presentation.UICommand.AddNewCommandFor`2.PerformExecute() in C:\projects\MoBi\src\MoBi.Presentation\UICommand\AddCommandFor.cs:line 48
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\ObjectUICommands.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\UICommandExtensions.cs:line 26
```

**Comment by msevestre** [comment]
I have tried quite some time but cannot reproduce. Will close for now
