### ISSUE TITLE
Error when opening a project

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1464]
The project here https://github.com/esqLABS/bug-reports/tree/cannot-open-simulation-294 was created with MoBi build 294. When trying to open it, the following error is thrown:

Application:
MoBi® 12.0.299

Sequence contains no matching element

Stack trace:
```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MoBi.Core.Services.TemplateResolverTask.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.<FindChangedBuildingBlocks>b__19_0(IBuildingBlock buildingBlock)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.FindChangedBuildingBlocks(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.refreshDisplayedSimulation(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToTree(ITreeNode`1 classificationNode, ClassifiableSimulation classifiableSimulation)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.AddClassifiableToTree[T](T classifiable, RootNodeType rootNodeType, Func`3 addClassifiableToTree)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.addClassifiableSimulationToSimulationRootFolder(ClassifiableSimulation classifiableSimulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.<AddProjectToTree>b__3_0(ClassifiableSimulation x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.AddProjectToTree(MoBiProject project)
   at MoBi.Presentation.Presenter.Main.ExplorerPresenter`2.AddProjectToTree(IProject project)
   at OSPSuite.Presentation.Presenters.AbstractExplorerPresenter`2.Handle(ProjectCreatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

I could already open other projects from build 294 with the current build (299).

**Comment by rwmcintosh** [comment]
This is probably the same cause as #1476, which has the steps to reproduce.

**Comment by rwmcintosh** [comment]
I might be able to recover this project if needed. I'll close the issue with a PR and you can PM me if needed.
