### ISSUE TITLE
Error when combining modules

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1465]
The project here https://github.com/esqLABS/bug-reports/tree/cannot-open-simulation-294 was created with MoBi build 294.

When trying to create a simulation with the following configuration:

![image](https://github.com/user-attachments/assets/0da027ad-991e-46a9-ad18-b91e50249345)

An error is thrown:

Application:
MoBi® 12.0.299

An item with the key 'Non-competitive NTCP transporter inhibition1' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:
```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Utility.Collections.Cache`2.AddRange(IEnumerable`1 range)
   at OSPSuite.Core.Domain.ValidationResult..ctor(IEnumerable`1 messages)
   at OSPSuite.Core.Domain.ValidationResult..ctor(ValidationResult[] validationResults)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validateModel(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(SimulationConfiguration simulationConfiguration, String modelName)
   at MoBi.Core.Domain.Services.SimulationFactory.createModel(SimulationConfiguration simulationConfiguration, String name)
   at MoBi.Core.Domain.Services.SimulationFactory.<>c__DisplayClass14_0.<CreateModelAndValidate>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by PavelBal** [comment]
The project cannot be opened any more.
