### ISSUE TITLE
Error opening GlucoseInsulinModel.mbp3 file

### ISSUE THREAD

**Issue by TechLabsFlo** [Open-Systems-Pharmacology/MoBi#1490]
Hi,

when opening MoBi (downloaded [here](https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v11.3)) tabs "modelling", "parameter indentification & Sensitivity", "Working Journal", "Import/Export" are greyed out.

When trying to open GlucoseInsulinModel.mbp3 (downloaded [here](https://github.com/Open-Systems-Pharmacology/Glucose-Insulin-Model)) the access to mobi.lock is denied. Any changes made to the project will not be saved. After opening the project anyway this error appears:

Application:
MoBi® 11.3.207

could not load collection by subselect: [OSPSuite.Infrastructure.Serialization.ORM.MetaData.CommandMetaData.Properties#System.Object[]]
[ SELECT properties0_.CommandId as commandid4_1_1_, properties0_.Id as id1_1_1_, properties0_.Name as name2_1_, properties0_.Id as id1_1_0_, properties0_.Name as name2_1_0_, properties0_.Value as value3_1_0_ FROM COMMAND_PROPERTIES properties0_ WHERE properties0_.CommandId in (select commandmet2_.Id FROM HISTORY_ITEMS this_ left outer join COMMANDS commandmet2_ on this_.CommandId=commandmet2_.Id left outer join COMMANDS commandmet3_ on commandmet2_.ParentId=commandmet3_.Id) ]
[SQL: SELECT properties0_.CommandId as commandid4_1_1_, properties0_.Id as id1_1_1_, properties0_.Name as name2_1_, properties0_.Id as id1_1_0_, properties0_.Name as name2_1_0_, properties0_.Value as value3_1_0_ FROM COMMAND_PROPERTIES properties0_ WHERE properties0_.CommandId in (select commandmet2_.Id FROM HISTORY_ITEMS this_ left outer join COMMANDS commandmet2_ on this_.CommandId=commandmet2_.Id left outer join COMMANDS commandmet3_ on commandmet2_.ParentId=commandmet3_.Id)]
-----------------------------------------------------
SQL logic error
no such table: COMMAND_PROPERTIES

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.LoadCollectionSubselect(ISessionImplementor session, Object[] ids, Object[] parameterValues, IType[] parameterTypes, IDictionary`2 namedParameters, IType type)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.LoadCollectionSubselect(ISessionImplementor session, Object[] ids, Object[] parameterValues, IType[] parameterTypes, IDictionary`2 namedParameters, IType type)
   at NHibernate.Loader.Collection.SubselectOneToManyLoader.Initialize(Object id, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultInitializeCollectionEventListener.OnInitializeCollection(InitializeCollectionEvent event)
   at NHibernate.Impl.SessionImpl.InitializeCollection(IPersistentCollection collection, Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.Initialize(Boolean writing)
   at NHibernate.Collection.Generic.PersistentGenericMap`2.ValuesWrapper.GetEnumerator()
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Infrastructure.Serialization.ORM.Mappers.CommandMetaDataToCommandMapper.MapFrom(CommandMetaData commandMetaData)
   at OSPSuite.Infrastructure.Serialization.ORM.Mappers.HistoryItemMetaDataToHistoryItemMapper.MapFrom(HistoryItemMetaData historyItemMetaData)
   at OSPSuite.Infrastructure.Serialization.ORM.History.HistoryManagerPersistor.<>c__DisplayClass6_0.<Load>b__0(HistoryItemMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Infrastructure.Serialization.ORM.History.HistoryManagerPersistor.Load(ISession session)
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by PavelBal** [comment]
Can you open/edit/save any other MoBi project?

Can it be that the downloaded file is located on a network drive?

**Comment by PavelBal** [comment]
Please try to re-install the suite and re-open the issue, if the problem persists.
