### ISSUE TITLE
Error when trying to create an individual

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1501]
Create new individual: 

Application:
MoBi® 12.0.311

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Unable to scan assembly.
Method 'ImportTablePoints' in type 'PKSim.Presentation.Presenters.Formulations.TableFormulationParameterPresenter' from assembly 'PKSim.Presentation, Version=12.0.313.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ImportTablePoints' in type 'PKSim.Presentation.Presenters.Compounds.TableSolubilityParameterPresenter' from assembly 'PKSim.Presentation, Version=12.0.313.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
-----------------------------------------------------
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Stack trace:
```
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Utility.Container.AssemblyScanner.Build()
   at OSPSuite.Utility.Container.ContainerExtensions.AddScanner(IContainer container, Action`1 scan)
   at PKSim.Presentation.BasePresenterRegister.RegisterInContainer(IContainer container)
   at PKSim.UI.Starter.PKSimStarterPresenterRegister.RegisterInContainer(IContainer container)
   at OSPSuite.Utility.Container.RegisterExpression.<Build>b__4_0(IRegister reg)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Utility.Container.RegisterExpression.Build()
   at OSPSuite.Utility.Container.ContainerExtensions.AddRegister(IContainer container, Action`1 containerInitialization)
   at PKSim.UI.Starter.ApplicationStartup.initializeForStartup(IContainer moBiContainer)
   at PKSim.UI.Starter.ApplicationStartup.Initialize()
   at PKSim.UI.Starter.IndividualCreator.CreateIndividual()
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MoBi.Presentation.Tasks.PKSimStarter.executeMethod(MethodInfo method, Object[] parameters)
   at MoBi.Presentation.Tasks.PKSimStarter.executeAndCloneBuildingBlock[TBuildingBlock](MethodInfo method)
   at MoBi.Presentation.Tasks.PKSimStarter.CreateIndividual()
   at MoBi.Presentation.UICommand.AddNewIndividualCommand.createBuildingBlockFromPKSim()
   at MoBi.Presentation.UICommand.AddNewFromPKSimCommand`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
This worked today for me on develop branch but there has been a PR or two merged already.

Let's try this tomorrow with tonight's nightlies.

**Comment by PavelBal** [comment]
Works with yesterday's nightlies.
