### ISSUE TITLE
Exception when creating a neighborhood

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1561]
Project from this issue: https://github.com/Open-Systems-Pharmacology/MoBi/issues/1497

In the "Diagram" view, start creating a neighborhood from "containerB" to "TopContainer":

Application:
MoBi® 12.0.340

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.ObjectPathFactory.addPathEntry(IEntity entity, ObjectPath objectPath)
   at OSPSuite.Core.Domain.ObjectPathFactory.CreateAbsoluteObjectPath(IEntity entity)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForNeighborhood.Add(IContainer firstNeighbor, IContainer secondNeighbor)
   at MoBi.Presentation.Presenter.SpaceDiagram.SpatialStructureDiagramPresenter.Link(IBaseNode node1, IBaseNode node2, Object portObject1, Object portObject2)
   at MoBi.UI.Views.BaseDiagram.MoBiBaseDiagramView.onLinkCreated(GoSelectionEventArgs e)
   at MoBi.UI.Views.BaseDiagram.MoBiBaseDiagramView.<>c__DisplayClass5_0.<InitializeResources>b__4()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by rwmcintosh** [comment]
TODO as I fix the initial bug report

- [ ]  The neighborhood connection is not drawn in these cases as well.
- [ ]  When I select the newly created neighborhood from the tree view

![image](https://github.com/user-attachments/assets/86d10ef1-9887-4501-8891-f78777896151)

**Comment by Yuri05** [comment]
At the moment, exception below comes with ANY project when trying to add a neighborhood with the diagram view of the spatial structure opened.

E.g. create a new module with the spatial structure, open the spatial structure and siwtch to the diagram view, then click on add nbhood button.

```
Application:
MoBi® 12.0.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Core.Domain.ObjectPath.op_Implicit(ObjectPath objectPath)
   at MoBi.UI.Diagram.DiagramManagers.SpatialStructureDiagramManager.GetNeighborHoodNodes(INeighborhoodBase neighborhoodBase) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.UI\Diagram\DiagramManagers\SpatialStructureDiagramManager.cs:line 130
   at OSPSuite.Presentation.Diagram.BaseDiagramManager`3.AddNeighborhood(INeighborhoodBase neighborhood)
   at OSPSuite.Presentation.Diagram.BaseDiagramManager`3.AddObjectBase(IContainerBase parent, IObjectBase objectBase, Boolean recursive, Boolean coupleAll)
   at OSPSuite.Presentation.Diagram.BaseDiagramManager`3.AddObjectBase(IObjectBase objectBase)
   at MoBi.Core.Commands.AddContainerToSpatialStructureCommand.AddTo(IContainer child, IContainer parent, IMoBiContext context) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Commands\AddContainerToSpatialStructureCommand.cs:line 38
   at MoBi.Core.Commands.AddObjectBaseCommand`2.ExecuteWith(IMoBiContext context) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Commands\AddObjectBaseCommand.cs:line 35
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at MoBi.Core.Extensions.MoBiCommandExtensions.RunCommand[T,TExecutionContext](T command, TExecutionContext context) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Extensions\MoBiCommandExtensions.cs:line 11
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddNew(TParent parent, IBuildingBlock buildingBlockToAddTo) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\Interaction\InteractionTaskFor.cs:line 81
   at MoBi.Presentation.UICommand.AddNewCommandFor`2.PerformExecute() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\UICommand\AddCommandFor.cs:line 29
   at MoBi.Presentation.UICommand.AddNewNeighborhoodCommand.PerformExecute() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\UICommand\AddCommandFor.cs:line 98
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
Diagrams!!!

![Image](https://github.com/user-attachments/assets/f215a50b-c2b7-4530-9827-5e59d078601a)
