### ISSUE TITLE
Error occurs when trying to reload a Parameter Identification from Working Journal

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#157]
Not possible to reload PI: 

"Value cannot be null.
Parameter name: source"
[Desktop.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1154982/Desktop.zip)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.MapFrom(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.MapDataTableFromColumns(IEnumerable`1 dataColumns)
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.Rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.EditObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataPresenter.Edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.SelectObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.<>c__DisplayClass2_0.<InitializeSubPresentersWith>b__0(IParameterIdentificationItemPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.InitializeSubPresentersWith(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at MoBi.Presentation.Tasks.SingleStartPresenterTask.StartForSubject[T](T subject)
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)

**Comment by msevestre** [comment]
Isn't the option kind of useless? Unless you reimport in the same project, it won't really work anyways (because observed data and simulations used in PI are not saved to WJ with the PI)

**Comment by msevestre** [comment]
@yuri05 I think this should be removed (same for SA).

**Comment by msevestre** [comment]
Another option would be to fail gracefully and remove everything that cannot be found.

**Comment by Yuri05** [comment]
>I think this should be removed (same for SA).

Agree.

**Comment by MarKrauss** [comment]
I find it really important to be able to store a PI in the WJ. My proposal would be that if a PI is added to the journal the related simulation is also stored and if one reloads the PI also the simulation is reloaded such that it is possible to get all information out of the PI again.

**Comment by MarKrauss** [comment]
I need to clarify the error a little bit. It is possible to reload. The error occurs when one double clicks on the reloaded PI afterwards

**Comment by msevestre** [comment]
My proposal would be to remove this feature for now because it does not work and will not work unless we change the concept of related item in the working journal.
@MarKrauss You can create a new feature request proposing to store not only the object (PI) but also all required items (simulation, observed data etc..). Right now this is simply not possible

**Comment by msevestre** [comment]
Observed data and Simulation are now exported with the Parameter identification.
When importing, it is imperative to import all in the correct order (or use the Import All button
