### ISSUE TITLE
Error after changing enzymes

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1592]
I have the same problem Today, Is it a bug?

Application:
MoBi® 11.3.207

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.MoBiApplicationController.CreatePresenterForSubject[TSubject](TSubject subject)
   at OSPSuite.Presentation.Core.ApplicationController.Open[TSubject](TSubject subject, ICommandCollector commandCollector)
   at MoBi.Presentation.MoBiApplicationController.Open[TSubject](TSubject subject, ICommandCollector commandCollector)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.editPresenterFor(T entity)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.editEntiy(T entity)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.Edit(T buildingBlock)
   at MoBi.Presentation.UICommand.EditCommandFor`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

_Originally posted by @amdreaanampg in https://github.com/Open-Systems-Pharmacology/MoBi/issues/1589#issuecomment-2427706309_

**Comment by rwmcintosh** [comment]
@amdreaanampg

> I made a mistake in the reaction setup. Instead of adding a molecule as an enzyme, I mistakenly added it as a transporter. I removed the components from the reaction to correct it and add new enzymes, but now the system won't allow me to edit anything. I’m not sure what the problem is. Any advice on how to fix this?

**Comment by rwmcintosh** [comment]
@amdreaanampg

> I cannot save my project because it shows me this 
> 
> Application:
> MoBi® 11.3.207
> 
> Value cannot be null.
> Parameter name: key
> 
> Stack trace:
> ```
> at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
>    at OSPSuite.Core.Serialization.Xml.SerializationContext.IdForString(String stringToCache)
>    at OSPSuite.Core.Serialization.Xml.FormulaUsablePathXmlSerializer.TypedSerialize(FormulaUsablePath objectPath, SerializationContext serializationContext)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.Serialize(Object objectToSerialize, TContext context)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.childNodeFor(TProperty child, TContext context)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.<>c__DisplayClass13_0.<Serialize>b__0(TProperty child)
>    at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Serialize(TObject objectToSerialize, TContext context)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedSerialize(TObject objectToSerialize, TContext context)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.Serialize(Object objectToSerialize, TContext context)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.childNodeFor(TProperty child, TContext context)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.<>c__DisplayClass13_0.<Serialize>b__0(TProperty child)
>    at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
>    at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Serialize(TObject objectToSerialize, TContext context)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedSerialize(TObject objectToSerialize, TContext context)
>    at OSPSuite.Core.Serialization.Xml.FormulaCacheXmlSerializer.TypedSerialize(FormulaCache formulaCache, SerializationContext serializationContext)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.Serialize(Object objectToSerialize, TContext context)
>    at OSPSuite.Core.Serialization.Xml.Extensions.XmlSerializerRepositoryExtensions.AddFormulaCacheElement(IXmlSerializerRepository`1 serializerRepository, XElement element, SerializationContext serializationContext)
>    at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedSerialize(TBuildingBlock bb, SerializationContext serializationContext)
>    at OSPSuite.Serializer.Xml.XmlSerializer`2.Serialize(Object objectToSerialize, TContext context)
>    at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.SerializeModelPart[T](T entityToSerialize)
>    at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.SerializeAsBytes[T](T entityToSerialize)
>    at MoBi.Core.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.serializeContent[T](MetaDataWithContent`1 metaDataWithContent, Object entity)
>    at MoBi.Core.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.serialize(EntityMetaData entityMetaData, Object entity)
>    at MoBi.Core.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.mapFrom(IWithId entityWithId)
>    at MoBi.Core.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.<>c__DisplayClass2_0.<MapFrom>b__0(IBuildingBlock x)
>    at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
>    at MoBi.Core.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.MapFrom(IMoBiProject project)
>    at MoBi.Core.Serialization.ORM.ProjectPersistor.projectMetaDataFrom(IMoBiProject project)
>    at MoBi.Core.Serialization.ORM.ProjectPersistor.Save(IMoBiProject project, IMoBiContext context)
>    at MoBi.Core.Serialization.ORM.ContextPersistor.Save(IMoBiContext context)
>    at MoBi.Presentation.Tasks.SerializationTask.SaveProject()
>    at MoBi.Presentation.Tasks.ProjectTask.saveProject()
>    at MoBi.Presentation.Tasks.ProjectTask.Save()
>    at MoBi.Presentation.UICommand.SaveProjectCommand.Execute()
>    at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
> ```
