### ISSUE TITLE
Cannot open protein expression

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1601]
Trying to open a protein expression:

Application:
MoBi® 12.0.356

Types OSPSuite.Core.Domain.Builder.ExpressionProfileBuildingBlock don't satisfy generic constraints of implementation type MoBi.Presentation.Tasks.Interaction.InitialConditionsTask`1 of component 'MoBi.Presentation.Tasks.Interaction.IInitialConditionsTask`1-MoBi.Presentation.Tasks.Interaction.InitialConditionsTask`1'. This is most likely a bug in your code.

Stack trace:
```
at Castle.MicroKernel.Handlers.DefaultGenericHandler.GetClosedImplementationType(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.DefaultGenericHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at OSPSuite.Presentation.Core.ApplicationController.Start[TPresenter]()
   at MoBi.Presentation.MoBiApplicationController.CreatePresenterForSubject[TSubject](TSubject subject)
   at OSPSuite.Presentation.Core.ApplicationController.Open[TSubject](TSubject subject, ICommandCollector commandCollector)
   at MoBi.Presentation.MoBiApplicationController.Open[TSubject](TSubject subject, ICommandCollector commandCollector)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.editPresenterFor(T entity)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.editEntity(T entity)
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.Edit(T buildingBlock)
   at MoBi.Presentation.UICommand.EditCommandFor`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
This was fixed very recently. I didn't create a separate issue, I had it fixed along with another one
