### ISSUE TITLE
Error (without effect?) when deleting molecule in reactions building block

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#166]
when deleting a molecule in reactions the following error occurs

"No component for supporting the service MoBi.Core.Services.IDiagramUpdater was found"

"at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at MoBi.Core.Domain.Model.MoBiContext.Resolve[T]()
   at MoBi.Core.Services.RemoveMoleculeFromReactionBuildingBlockCommand.ExecuteWith(IMoBiContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.RemoveMoleculeNode(MoleculeNode moleculeNode)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.removeItem(GoObject itemToDelete)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.RemoveSelection(IReadOnlyList`1 objectsToBeRemoved)
   at MoBi.UI.Views.ReactionDiagram.ReactionDiagramView.OnSelectionDeleting(CancelEventArgs e)
   at MoBi.UI.Views.BaseDiagram.MoBiBaseDiagramView.<>c__DisplayClass5_1.<InitializeResources>b__3()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
[ErrorReactions.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1207848/ErrorReactions.zip)
"

**Comment by MarKrauss** [comment]
seems to have not effect on modeling

**Comment by msevestre** [comment]
Duplicate (reported by you lol)
https://github.com/Open-Systems-Pharmacology/MoBi/issues/110

**Comment by MarKrauss** [comment]
Haha ok, sorry...
