### ISSUE TITLE
Drag & drop of Building Blocks between modules

### ISSUE THREAD

**Issue by VanessaBa** [Open-Systems-Pharmacology/MoBi#1721]
It's possible to drag and drop a BB into another module....followed by several exceptions. 
I guess it should just not be supported.... 

Application:
MoBi® 12.0.377

Sequence contains no matching element

Stack trace:
```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MoBi.Core.Services.TemplateResolverTask.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.TemplateBuildingBlockFor[TBuildingBlock](TBuildingBlock buildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.<FindChangedBuildingBlocks>b__19_0(IBuildingBlock buildingBlock)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForSimulation.FindChangedBuildingBlocks(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.refreshDisplayedSimulation(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.Handle(SimulationStatusChangedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by rwmcintosh** [comment]
I think we should keep it, just fix the exceptions 😉

**Comment by rwmcintosh** [comment]
Need this first
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2379
