### ISSUE TITLE
sbml importing failure

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/MoBi#176]
Hi,
I tried to open a few sbml models from the biomodels databse using the "Import SBML" functionality in MoBi but it doesn't work and every time I get this error:
Application:
MoBi 7.1.0 - Build 66

The type initializer for 'libsbmlcs.libsbmlPINVOKE' threw an exception.
-----------------------------------------------------
The type initializer for 'SWIGExceptionHelper' threw an exception.
-----------------------------------------------------
Unable to load DLL 'libsbmlcs': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Stack trace:
```
at libsbmlcs.libsbmlPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_libsbml(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at libsbmlcs.libsbmlPINVOKE.SWIGExceptionHelper..cctor()
 --- End of inner exception stack trace ---
   at libsbmlcs.libsbmlPINVOKE.SWIGExceptionHelper..ctor()
   at libsbmlcs.libsbmlPINVOKE..cctor()
 --- End of inner exception stack trace ---
   at libsbmlcs.libsbmlPINVOKE.readSBML(String jarg1)
   at libsbmlcs.libsbml.readSBML(String filename)
   at MoBi.Core.SBML.SBMLTask.GetModel(String filename)
   at MoBi.Core.SBML.SBMLTask.ImportModelFromSBML(String filename, IMoBiProject project)
   at MoBi.Presentation.Tasks.ProjectTask.OpenSBMLModel()
   at MoBi.Presentation.UICommand.ImportSbmlUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
Thanks,
Ahmed.

**Comment by msevestre** [comment]
Looks like a file is missing in the setup

**Comment by Yuri05** [comment]
libsbmlcs.dll is missing in the setup.

Workaround: extract the dll from the attached archive into your MoBi installation folder
[libsbmlcs.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1317297/libsbmlcs.zip)

**Comment by aelmokadem** [comment]
Thanks for your reply. I placed the file in the installation folder and tried two sbml files from biomodels. The first opened smoothly while the second caused mobi to shutdown. Perhaps there is something wrong with the file itself.

**Comment by msevestre** [comment]
@aelmokadem MoBi should not shut down if the file is corrupted. Could you create another issue an attach the file there? That would be super helpful. In the meantime, we are going to correct this issue with the file missing in the upcoming release

**Comment by aelmokadem** [comment]
Sure I will. Thanks a lot Michael.
