### ISSUE TITLE
export ODEs failure

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/MoBi#185]
Hi,
I had a MoBi model that I tried to export the ODEs for but exporting failed and gave me this error message:
Application:
MoBi 7.1.0 - Build 66

Could not load file or assembly 'Microsoft.WindowsAPICodePack, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Stack trace:
```
at OSPSuite.UI.Services.DialogCreator.AskForFolder(String title, String directoryKey, String defaultDirectory)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.AskForFolder(String title, String directoryKey)
   at MoBi.Presentation.Tasks.Edit.EditTasksForSimulation.ExportMatlabDifferentialSystem(IMoBiSimulation simulation)
   at MoBi.Presentation.UICommand.ExportMatlabODEUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
I also tried the same thing with the GlucoseInsulinGlucagon model and got the same error.
Can you please advise?
Thank you.

**Comment by msevestre** [comment]
@aelmokadem This is a known issue that will be fixed in the next release
In the meantime, the workaround would be to copy the dll in the attached zip file in your MoBi folder

**Comment by msevestre** [comment]
[Microsoft.WindowsAPICodePack.dll.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1333431/Microsoft.WindowsAPICodePack.dll.zip)

**Comment by aelmokadem** [comment]
@msevestre  Thanks a lot Michael and I apologize for all these issues I am throwing at you guys.

**Comment by msevestre** [comment]
@aelmokadem Absolutely no need to apologize. Keep them coming :). This is very useful
Those bugs will all be sorted out in the upcoming release. These missing dlls are very annoying and happened when we moved to open source.

**Comment by aelmokadem** [comment]
I can totally imagine things getting lost in the transition and till the next release, I think you guys are doing just fine addressing all the issues.
