### ISSUE TITLE
Opening MoBi project raised an error and saved the project with size 0 KB

### ISSUE THREAD

**Issue by AnneGrimbs** [Open-Systems-Pharmacology/MoBi#244]
Application:
MoBi 7.2.1 - Build 2

could not execute query
[ SELECT this_.Id as Id1_0_1_, this_.CommandId as Comman2_0_1_, this_.Discriminator as Discri3_0_1_, this_.CommandInverseId as Comman4_0_1_, this_.CommandType as Comman5_0_1_, this_.ObjectType as Object6_0_1_, this_.Description as Descri7_0_1_, this_.ExtendedDescription as Extend8_0_1_, this_.Visible as Visibl9_0_1_, this_.Comment as Comme10_0_1_, this_.Sequence as Seque11_0_1_, this_.ParentId as Paren12_0_1_, commandmet2_.Id as Id1_0_0_, commandmet2_.CommandId as Comman2_0_0_, commandmet2_.Discriminator as Discri3_0_0_, commandmet2_.CommandInverseId as Comman4_0_0_, commandmet2_.CommandType as Comman5_0_0_, commandmet2_.ObjectType as Object6_0_0_, commandmet2_.Description as Descri7_0_0_, commandmet2_.ExtendedDescription as Extend8_0_0_, commandmet2_.Visible as Visibl9_0_0_, commandmet2_.Comment as Comme10_0_0_, commandmet2_.Sequence as Seque11_0_0_, commandmet2_.ParentId as Paren12_0_0_ FROM COMMANDS this_ left outer join COMMANDS commandmet2_ on this_.ParentId=commandmet2_.Id ]
[SQL: SELECT this_.Id as Id1_0_1_, this_.CommandId as Comman2_0_1_, this_.Discriminator as Discri3_0_1_, this_.CommandInverseId as Comman4_0_1_, this_.CommandType as Comman5_0_1_, this_.ObjectType as Object6_0_1_, this_.Description as Descri7_0_1_, this_.ExtendedDescription as Extend8_0_1_, this_.Visible as Visibl9_0_1_, this_.Comment as Comme10_0_1_, this_.Sequence as Seque11_0_1_, this_.ParentId as Paren12_0_1_, commandmet2_.Id as Id1_0_0_, commandmet2_.CommandId as Comman2_0_0_, commandmet2_.Discriminator as Discri3_0_0_, commandmet2_.CommandInverseId as Comman4_0_0_, commandmet2_.CommandType as Comman5_0_0_, commandmet2_.ObjectType as Object6_0_0_, commandmet2_.Description as Descri7_0_0_, commandmet2_.ExtendedDescription as Extend8_0_0_, commandmet2_.Visible as Visibl9_0_0_, commandmet2_.Comment as Comme10_0_0_, commandmet2_.Sequence as Seque11_0_0_, commandmet2_.ParentId as Paren12_0_0_ FROM COMMANDS this_ left outer join COMMANDS commandmet2_ on this_.ParentId=commandmet2_.Id]
-----------------------------------------------------
SQL logic error or missing database
no such table: COMMANDS

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at OSPSuite.Infrastructure.Serialization.ORM.MetaData.CommandMetaDataRepository.LoadFromSession(ISession session)
   at OSPSuite.Infrastructure.Serialization.ORM.MetaData.HistoryItemMetaDataRepository.All(ISession session)
   at OSPSuite.Infrastructure.Serialization.ORM.History.HistoryManagerPersistor.allHistoryItemMetaData(ISession session)
   at OSPSuite.Infrastructure.Serialization.ORM.History.HistoryManagerPersistor.Load(ISession session)
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
Hi @AnneGrimbs,

This error typically occurs when trying to open a file that was not finished downloading or when trying  to access a path where there are no  write access etc..

Do you have any info that you could share with us explaining how you received this error? Especially where was the file located, did you create it or was it downloaded etc..
