### ISSUE TITLE
7.3 beta, portable MoBi version: Unhandled exception after trying to close MoBi

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/MoBi#264]
Using portable PK-Sim/MoBi: After sending a PK-Sim simulation to MoBi and subsequently directly closing  MoBi, I get an unhandled exception:

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Open Systems Pharmacology\MoBi\7.3\ApplicationSettings.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at System.Xml.Linq.XDocument.Save(String fileName)
   at MoBi.Presentation.Serialization.Xml.SettingsPersistor`1.Save()
   at MoBi.Presentation.UICommand.ExitCommand.Execute()
   at MoBi.Presentation.Presenter.MoBiMainViewPresenter.FormClosing()
   at MoBi.UI.Views.MoBiMainView.mainViewFormClosing(Object sender, CancelEventArgs e)
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at DevExpress.XtraBars.Ribbon.RibbonForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by msevestre** [comment]
This should actually be fixed with latest version

**Comment by msevestre** [comment]
All right. I thought this would be taken care of with another change but clearly not. This should now really be fixed
