### ISSUE TITLE
Working Journal misbehaves

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#283]
If I look at a WJ page, I see "Title", text, and a list of tags below the ribbon field. Clicking on the leftmost tab of the ribbon (see graph, red circle) lets the WJ act up: By repeated clicking, you can now toggle between "Text only" or "Title" and "Tags", but you will not get back to the original view unless you quit and restart MoBi. 

Re-opening the same project or another with a WJ will produce the following Exception error:
Application:
MoBi 7.2.2 - Build 2

Invisible or disabled control cannot be activated

Stack trace:
```
at System.Windows.Forms.ContainerControl.SetActiveControlInternal(Control value)
   at System.Windows.Forms.ContainerControl.set_ActiveControl(Control value)
   at OSPSuite.UI.Views.Journal.JournalPageEditorView.BindTo(JournalPageDTO journalPageDTO)
   at OSPSuite.Presentation.Presenters.Journal.JournalPageEditorPresenter.Edit(JournalPage journalPage)
   at OSPSuite.Presentation.Presenters.Journal.JournalPageEditorPresenter.Handle(EditJournalPageStartedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_0`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

![grafik](https://user-images.githubusercontent.com/27352743/40542064-c79f1b6a-601e-11e8-9f50-cf580cd49cc3.png)

**Comment by msevestre** [comment]
We should remove this option. Offering unsupported button is not a good idea. I am glad that hardly anyone is using this feature :))

**Comment by UlrichSi** [comment]
Either remove it or let it behave like the corresponding (I believe) PK-Sim MoBi button does.

![grafik](https://user-images.githubusercontent.com/27352743/40601058-df6b3440-6253-11e8-85f7-4872041d0715.png)
