### ISSUE TITLE
Load Observed Data: Invalid file causes exception rather than proper error handling

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#289]
Loading any non-PKML file (e.g., a plain text file) using "Load Observed Data" will throw the following exception:

Application:
MoBi 7.2.2 - Build 2

Data at the root level is invalid. Line 1, position 1.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.ObservedDataTask.LoadObservedDataIntoProject()
   at MoBi.Presentation.UICommand.LoadDataRepositoryUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Fixed.
