### ISSUE TITLE
Error Export PDF Project Report

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#420]
Just opened project and clicked on Project Report.
Selected Extended Report (with Figures).

Project attached.

Application:
MoBi® 8.0.21

One or more errors occurred.
-----------------------------------------------------
A generic error occurred in GDI+.

Stack trace:
```
at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at MoBi.Presentation.Tasks.DiagramModelToImageTask.ExportTo[T](T withDiagramModel, String imageFilePath)
   at MoBi.Core.Reporting.SpatialStructureReporter.Report(IMoBiSpatialStructure spatialStructure, OSPSuiteTracker buildTracker)
   at OSPSuite.Infrastructure.Reporting.OSPSuiteTeXReporter`1.Report(Object objectToReport, OSPSuiteTracker buildTracker)
   at MoBi.Core.Reporting.BuildingBlocksReporter`1.Report(IReadOnlyCollection`1 buildingBlocksToReport, OSPSuiteTracker buildTracker)
   at MoBi.Core.Reporting.ProjectReporter.Report(IMoBiProject project, OSPSuiteTracker buildTracker)
   at OSPSuite.Infrastructure.Reporting.OSPSuiteTeXReporter`1.Report(Object objectToReport, OSPSuiteTracker buildTracker)
   at OSPSuite.Infrastructure.Reporting.ReportingTask.<CreateReportAsync>d__6.MoveNext()
 --- End of inner exception stack trace ---
```

[Ex_ADC_8.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/3697161/Ex_ADC_8.zip)

**Comment by msevestre** [comment]
Can you close MoBi and start again? It looks more like a memory issue to me. Nothing we can do here
