### ISSUE TITLE
Salvage corrupt MoBi project file?

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/MoBi#425]
I seem to have run into the same issue as described in #411. Is there a way to salvage the corrupt MoBi project file?

```
Value cannot be null.
Parameter name: key

at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Core.Domain.UnitSystem.Dimension.AddUnit(Unit unit)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.DimensionXmlSerializer.TypedDeserialize(Dimension dimension, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Serializer.MergedDimensionFactorySerializer.TypedDeserialize(DimensionFactory objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiProjectXmlSerializer.TypedDeserialize(MoBiProject project, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, IMoBiProject project, SerializationContext serializationContext)
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeContent[T](MetaDataContent content, SerializationContext serializationContext)
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Load(IMoBiContext context)
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
Yes. If you send me the file (michael@design2code.ca) or upload it here, I should be able to save it

**Comment by PavelBal** [comment]
Whaaat it was possible to recover it???

**Comment by msevestre** [comment]
@PavelBal Yes I can recover from this specific issue. This is a regression that has been fixed in the current nightly of MoBi
