### ISSUE TITLE
Error when loading the same simulation from pkml twice

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#474]
Actually, this may also be a slightly different simulation - I think it happens when the names of the used building blocks are the same.

1) Export any simulation to a pkml.
2) Load it in an empty MoBi-Project
3) Try to load the same simulation again:

```
Application:
MoBi® 8.0.21

Id 03R1AeOz_0efDri3id_4vg not unique

Stack trace:
```
at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](XElement element, IMoBiProject project, Int32 version)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass18_0`1.<LoadMany>b__0(XElement element)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.ProjectTask.loadSimulationTransferFromFileUsingDimensionMode(String fileName, ReactionDimensionMode dimensionMode)
   at MoBi.Presentation.Tasks.ProjectTask.LoadSimulationTransferDataFromFile(String fileName)
   at MoBi.Presentation.Tasks.ProjectTask.<>c__DisplayClass15_0.<loadSimulationFromFileInProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
```

**Comment by abdullahhamadeh** [comment]
Any ideas if there is a quick and temporary workaround for this?  The scenario @PavelBal describes here has come up quite a few times with me.

**Comment by PavelBal** [comment]
No, unfortunately no workaround. Extremely annoying.

**Comment by msevestre** [comment]
Hum..
Can't you simply load the simulation in R and export it as pkml? We have introduced a new behavior that  resets all Ids by default I believe.

**Comment by msevestre** [comment]
@PavelBal ??

**Comment by PavelBal** [comment]
Actually just tried to load the same pkml saved from R twice - no luck.

**Comment by msevestre** [comment]
I just tried and it works
![image](https://user-images.githubusercontent.com/1041237/110482544-c60bd700-80b6-11eb-9fb8-36c3e3d3c19a.png)

**Comment by msevestre** [comment]
You need to use the version with the resetId parameter in LoadSimulation. It was not available in the version 9 I believe

**Comment by msevestre** [comment]
@abdullahhamadeh @PavelBal This is solved in v10 and should be available in nightly

**Comment by PavelBal** [comment]
I tried it with the current nightly and got the same error. Would be amazing if this can be solved for V10.

Note: PKML was created with V9, does the fix require the simulation be created in V10?

**Comment by PavelBal** [comment]
I could not figure out when it happens and when not, will report when I have a case.

**Comment by msevestre** [comment]
I can reproduce with your example. WTF
