### ISSUE TITLE
Error opening old project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#476]
Trying to open the project from https://github.com/Open-Systems-Pharmacology/MoBi/issues/475 in MoBi 9 produces the error below.

```
Application:
MoBi® 9.0.0

Dimension 'Mass per area' not available in DimensionFactory.

Stack trace:
at OSPSuite.Core.Domain.UnitSystem.DimensionFactory.Dimension(String name)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.DimensionByName(String dimensionName)
   at OSPSuite.Core.Serialization.Xml.DimensionAttributeMapper.ConvertFrom(String attributeValue, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlAttributeMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.FormulaCacheXmlSerializer.TypedDeserialize(FormulaCache formulaCache, XElement formulaCacheNode, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.Extensions.XmlSerializerRepositoryExtensions.DeserializeFormulaCacheIn(IXmlSerializerRepository`1 serializerRepository, XElement element, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedDeserialize(TBuildingBlock bb, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement outputToDeserialize, SerializationContext serializationContext) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\Xml\Serializer\MoBiSimulationXmlSerializer.cs:line 31
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 122
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, IMoBiProject project, SerializationContext serializationContext) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 93
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeContent[T](MetaDataContent content, SerializationContext serializationContext) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 101
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.addSimulationToProject(SimulationMetaData simulationMetaData, SerializationContext serializationContext) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 90
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 60
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 80
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Load(IMoBiContext context) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 56
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath) in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Core\Serialization\ORM\ContextPersistor.cs:line 78
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0() in C:\SW-Dev\MoBi\branches\9.0\src\MoBi.Presentation\Tasks\SerializationTask.cs:line 57
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
@Yuri05 Are you sure you have the latest dim locally?
https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml#L476

It is defined so it should work

**Comment by Yuri05** [comment]
is the latest dimensions used in MoBi9? Because I'm using the dev version of MoBi9

**Comment by msevestre** [comment]
don't forget to update the submodule and postclean

**Comment by Yuri05** [comment]
ok, dimensions in Mobi must be updated, currently not the latest version is used. will open the new issue for that and close this one
