### ISSUE TITLE
Unable to save A new project after modifying the spatial structure

### ISSUE THREAD

**Issue by Mahmood1212** [Open-Systems-Pharmacology/MoBi#503]
Hello All,

MoBi is giving me this letter below when I am trying to save my new file:

More on the issue: I have added a neighborhood to a nasal depot spatial structure of the drug I am working on right now (the file was saving normally before), I have added one between it and the plasma of stomach compartment, and another 2 with the plasma and interstitial lung compartments and what follows was the message below. 

Thank you for your help in advance.

Mahmoud

PS. the file attached is not updated since MoBi didn't save it.

[amiloride nasal Latest July 2020.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/4996164/amiloride.nasal.Latest.July.2020.zip)

Application:
MoBi® 8.0.21

Begin failed with SQL exception
-----------------------------------------------------
attempt to write a readonly database
attempt to write a readonly database

Stack trace:
```
at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteTransaction.Begin(Boolean deferredLock)
   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
 --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   at NHibernate.Impl.AbstractSessionImpl.BeginTransaction()
   at MoBi.Core.Serialization.ORM.ContextPersistor.Save(IMoBiContext context)
   at MoBi.Presentation.Tasks.SerializationTask.SaveProject()
   at MoBi.Presentation.Tasks.ProjectTask.saveProject()
   at MoBi.Presentation.Tasks.ProjectTask.Save()
   at MoBi.Presentation.UICommand.SaveProjectCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
The message says that the file is read-only

Is the file read-only?

**Comment by Mahmood1212** [comment]
Yes it was. No idea how it switched automatically to read-only 
Thank you very much.

**Comment by msevestre** [comment]
No problem. I am going to create an issue to make sure that we get a better error message. This is not the first time that people get surprised by this

**Comment by msevestre** [comment]
Note to self: This also probably applies to PK-Sim
