### ISSUE TITLE
Requested value 'BiDirectional' was not found.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#547]
When trying to load a simulation with bi-directional transport, the error message is thrown:

```
Requested value 'BiDirectional' was not found.

at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at OSPSuite.Serializer.Attributes.EnumAttributeMapper`2.ConvertFrom(String attributeValue, TContext context)
   at OSPSuite.Serializer.Xml.XmlAttributeMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.MoleculeBuilderXmlSerializer.TypedDeserialize(MoleculeBuilder moleculeBuilder, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedDeserialize(TBuildingBlock bb, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](XElement element, IMoBiProject project, Int32 version)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass18_0`1.<LoadMany>b__0(XElement element)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.ProjectTask.loadSimulationTransferFromFileUsingDimensionMode(String fileName, ReactionDimensionMode dimensionMode)
   at MoBi.Presentation.Tasks.ProjectTask.LoadSimulationTransferDataFromFile(String fileName)
   at MoBi.Presentation.Tasks.ProjectTask.<>c__DisplayClass15_0.<loadSimulationFromFileInProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

PK-Sim project and pkml-simulation are attached.
[TestSims.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/6243073/TestSims.zip)

**Comment by msevestre** [comment]
Yeah it's because MoBi uses an outdated opsuite.core. It will work when we update
