### ISSUE TITLE
Error opening results in  Lung MoBi model

### ISSUE THREAD

**Issue by sivaaodh** [Open-Systems-Pharmacology/MoBi#562]
Application:
MoBi® 9.1.1

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Presentation.Services.Charts.ChartTemplatingTask.<>c.<allCurvesForSimulation>b__19_0(CurveChart x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Presentation.Services.Charts.ChartTemplatingTask.CurvePlotting(IReadOnlyCollection`1 simulations, DataColumn dataColumn)
   at OSPSuite.Presentation.Services.Charts.ChartTemplatingTask.<>c__DisplayClass17_0.<addSimulationOutputs>b__2(DataColumn column)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Services.Charts.ChartTemplatingTask.addSimulationOutputs(IChartEditorPresenter chartEditorPresenter, IReadOnlyCollection`1 allAvailableColumns, IReadOnlyCollection`1 simulations, Boolean addCurveIfNoSourceDefined)
   at OSPSuite.Presentation.Services.Charts.ChartTemplatingTask.UpdateDefaultSettings(IChartEditorPresenter chartEditorPresenter, IReadOnlyCollection`1 allAvailableColumns, IReadOnlyCollection`1 simulations, Boolean addCurveIfNoSourceDefined, Action customUpdate)
   at MoBi.Presentation.Tasks.ChartTemplatingTask.InitFromTemplate(ICache`2 simulations, CurveChart chart, IChartEditorPresenter chartEditorPresenter, CurveChartTemplate chartTemplate, Func`2 curveNameDefinition, Boolean triggeredManually, Boolean propogateChartChangeEvent)
   at MoBi.Presentation.Presenter.ChartPresenter.LoadFromTemplate(CurveChartTemplate chartTemplate, Boolean triggeredManually, Boolean propagateChartChangeEvent)
   at MoBi.Presentation.Presenter.ChartPresenter.Show(CurveChart chart, IReadOnlyList`1 dataRepositories, CurveChartTemplate defaultTemplate)
   at MoBi.Presentation.Presenter.ProjectChartPresenter.Show(CurveChart chart, IReadOnlyList`1 data)
   at MoBi.Presentation.Tasks.ChartTasks.ShowChart(CurveChart chart, IReadOnlyList`1 data)
   at MoBi.Presentation.Tasks.ChartTasks.ShowData(IReadOnlyList`1 data)
   at MoBi.Presentation.Tasks.ChartTasks.ShowData(DataRepository dataRepository)
   at MoBi.Presentation.UICommand.ShowDataRepositoryUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Is there any chance you can attach the project as well (as a zip file)

**Comment by sivaaodh** [comment]
Sure. Please find the attached project file.

Thank you
siva

**Comment by msevestre** [comment]
@sivaaodh It's not there. you need to attach it in the issue. Email removes those
