### ISSUE TITLE
Nightly build failing

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#621]
```
Errors, Failures and Warnings
1) Failed : MoBi.Core.SBML.PassiveTransportReactionImporterTests.ShouldRaiseOnInvalidFileConvertion
  Expected: instance of <MoBi.Core.Exceptions.MoBiException>
  But was:  <System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at libsbmlcs.libsbmlPINVOKE.SBMLDocument_setLevelAndVersion__SWIG_2(HandleRef jarg1, Int64 jarg2, Int64 jarg3)
   at libsbmlcs.SBMLDocument.setLevelAndVersion(Int64 level, Int64 version)
   at MoBi.Engine.Sbml.SbmlTask.convertSBML(SBMLDocument sbmlDoc) in C:\projects\mobi\src\MoBi.Engine\Sbml\SBMLTask.cs:line 135
   at MoBi.Engine.Sbml.SbmlTask.GetModel(String filename) in C:\projects\mobi\src\MoBi.Engine\Sbml\SBMLTask.cs:line 110
   at MoBi.Engine.Sbml.SbmlTask.ImportModelFromSbml(String filename, IMoBiProject project) in C:\projects\mobi\src\MoBi.Engine\Sbml\SBMLTask.cs:line 46
   at MoBi.Core.SBML.PassiveTransportReactionImporterTests.<ShouldRaiseOnInvalidFileConvertion>b__2_0() in C:\projects\mobi\Tests\MoBi.Tests\Core\SBML\ReactionImporterSpecs.cs:line 175
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.getExceptionFromPerforming(Action work)>
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeAnInstanceOf(Object item, Type type)
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeAnInstanceOf[T](Object item)
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldThrowAn[TException](Action workToPerform)
   at MoBi.Core.SBML.PassiveTransportReactionImporterTests.ShouldRaiseOnInvalidFileConvertion() in C:\projects\mobi\Tests\MoBi.Tests\Core\SBML\ReactionImporterSpecs.cs:line 175
```

**Comment by abdelr** [comment]
@msevestre Is this on Develop? The test is green locally on my side.
