### ISSUE TITLE
MSV: Error when editing aliases in formulas

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#672]
In any formula in the MSV BB, try to change the name of an existing alias or create a new one and set its name:

Application:
MoBi® 10.0.122

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.Formulas.FormulaExtensions.FormulaUsablePathBy(IFormula formula, String alias)
   at MoBi.Core.Commands.EditFormulaAliasCommand.ExecuteWith(IMoBiContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at MoBi.Presentation.Tasks.MoBiFormulaTask.EditAliasInFormula(IFormula formula, String newAlias, String oldAlias, IFormulaUsablePath formulaUsablePath, IBuildingBlock buildingBlock)
   at MoBi.Presentation.Presenter.EditFormulaPathListPresenter.SetAlias(String newAlias, String oldAlias, IFormulaUsablePath formulaUsablePath)
   at MoBi.UI.Views.EditFormulaPathListView.<>c__DisplayClass15_0.<InitializeBinding>b__16()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
Cannot reproduce.
