### ISSUE TITLE
Import parameter values from XLS: error when a cell contains formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#678]
In any MoBi project, right click on a Parameter Start Values Building Block and select "Import...". Select the attached file and the sheet "Midazolam".

[ModelParameters.xlsx](https://github.com/Open-Systems-Pharmacology/MoBi/files/7950765/ModelParameters.xlsx)

Application:
MoBi® 10.0.122

Error evaluating cell Midazolam!A2
-----------------------------------------------------
_xlfn.CONCAT

Stack trace:
```
at NPOI.SS.Formula.UserDefinedFunction.Evaluate(ValueEval[] args, OperationEvaluationContext ec)
   at NPOI.SS.Formula.OperationEvaluatorFactory.Evaluate(OperationPtg ptg, ValueEval[] args, OperationEvaluationContext ec)
   at NPOI.SS.Formula.WorkbookEvaluator.EvaluateFormula(OperationEvaluationContext ec, Ptg[] ptgs)
   at NPOI.SS.Formula.WorkbookEvaluator.EvaluateAny(IEvaluationCell srcCell, Int32 sheetIndex, Int32 rowIndex, Int32 columnIndex, EvaluationTracker tracker)
 --- End of inner exception stack trace ---
   at NPOI.SS.Formula.WorkbookEvaluator.EvaluateAny(IEvaluationCell srcCell, Int32 sheetIndex, Int32 rowIndex, Int32 columnIndex, EvaluationTracker tracker)
   at NPOI.SS.Formula.WorkbookEvaluator.Evaluate(IEvaluationCell srcCell)
   at NPOI.XSSF.UserModel.BaseXSSFFormulaEvaluator.EvaluateFormulaCellValue(ICell cell)
   at NPOI.SS.Formula.BaseFormulaEvaluator.Evaluate(ICell cell)
   at OSPSuite.Infrastructure.Import.Core.DataSourceFileReaders.ExcelReader.getCellStringValue(ICell cell)
   at OSPSuite.Infrastructure.Import.Core.DataSourceFileReaders.ExcelReader.MoveToNextRow()
   at OSPSuite.Infrastructure.Import.Services.ImportFromExcelTask.dataTables(String fileName, String sheetName, Boolean firstRowAsCaption)
   at OSPSuite.Infrastructure.Import.Services.ImportFromExcelTask.getDataTables(String fileName, String sheetName, Boolean firstRowAsCaption)
   at OSPSuite.Infrastructure.Import.Services.ImportFromExcelTask.GetDataTables(String filePath, String sheetName, Boolean firstRowAsCaption)
   at MoBi.Presentation.Presenter.AbstractQuantitiesImporterPresenter.importedDataTableFromFile()
   at MoBi.Presentation.Presenter.AbstractQuantitiesImporterPresenter.StartImport()
   at MoBi.UI.Views.ImportQuantityView.<InitializeBinding>b__9_11()
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
Fixed.
