### ISSUE TITLE
Rollback error

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#693]
[RollbackError_693.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/8186565/RollbackError_693.zip)

- Open the project
- Open Molecules-BB and select TMEFF2
- Change the value of the parameter `Relative expression` from `NaN` to `0`
- Open PSV-BB and "Extend"
- Open "History" and select "Undo":

Application:
MoBi® 10.0.122

Key '0' could not be found

Stack trace:
```
at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__10_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.StringForId(Int32 stringId)
   at OSPSuite.Core.Serialization.Xml.ObjectPathXmlSerializer`1.TypedDeserialize(T objectPath, XElement objectPathElement, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.StartValueXmlSerializer`1.TypedDeserialize(T startValue, XElement startValueElement, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, IMoBiProject project, SerializationContext serializationContext)
   at MoBi.Core.Domain.Model.MoBiContext.Deserialize[T](Byte[] serializationStream)
   at MoBi.Core.Commands.AddStartValueToBuildingBlockCommand`1.RestoreExecutionData(IMoBiContext context)
   at OSPSuite.Core.Commands.Core.RollBackCommand`1.<>c__DisplayClass3_0.<Execute>b__0(IReversibleCommand`1 command)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Commands.Core.RollBackCommand`1.Execute(TExecutionContext context)
   at OSPSuite.Core.Commands.Core.HistoryManager`1.RollBackTo(Int32 state)
```

**Comment by PavelBal** [comment]
Not reproducible with the new concept.
