### ISSUE TITLE
Rerunning PI task after conversion from MoBi 6.4 throws error

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#70]
Use the project from issue #67, attached to YT 46-7469. Open any PI taks, try rerunning it. An error is thrown:

Application:
MoBi 7.1.0 - Build 31

Specified argument was out of the range of valid values.
Parameter name: StandardParameterIdentificationRunMode

Stack trace:
```
at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunFactory.CreateFor(ParameterIdentification parameterIdentification, CancellationToken cancellationToken) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunFactory.cs:line 37
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<>c__DisplayClass12_0.<createParameterIdentificationRuns>b__0() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<createParameterIdentificationRuns>d__12.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<StartAsync>d__6.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunner.<Run>d__8.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunner.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Extensions\TaskExtensions.cs:line 26
```

**Comment by msevestre** [comment]
Please try with latest setup. This has been fixed in build #34

**Comment by UlrichSi** [comment]
Then please make sure the latest setup is installed on the test machine!

**Comment by msevestre** [comment]
Please assign this issue to Thomas. We do not have access to test machine.

**Comment by msevestre** [comment]
@Yuri05 please ensure that latest setup is installed nightly on test machines.

**Comment by msevestre** [comment]
This if fixed. Please reopen if the issue persists

**Comment by UlrichSi** [comment]
looks like it works ok in build 34
