### ISSUE TITLE
SBML import crashes MoBi

### ISSUE THREAD

**Issue by BaronvonderHeyden** [Open-Systems-Pharmacology/MoBi#723]
Hello,

I tried to import ("File" -> "open SBML model") a curated model from Biomodels (SBML level 3 version 1) into MoBi. But opening the SBML file (sometimes) makes MoBi crash.

Curiously, this is not always the case. Most of the times (80%) MoBi crashes simply without any warning whatsoever. But at least once I also got a warning while importing the file, without it crashing (* see Error message at the end)

And twice I even (seemingly) managed to import the model.

I am using MoBi 11, build 138. The model I tried to import is from Biomodels (https://www.ebi.ac.uk/biomodels/BIOMD0000001029#Files)

*Application:
MoBi® 11.0.138

Unable to cast object of type 'libsbmlcs.SBase' to type 'libsbmlcs.Reaction'.

Stack trace:
```
at libsbmlcs.Model.getReaction(Int64 n)
   at MoBi.Engine.Sbml.ReactionImporter.Import(Model model)
   at MoBi.Engine.Sbml.SBMLImporter.DoImport(Model sbmlModel, IMoBiProject moBiProject, SBMLInformation sbmlInformation, ICommandCollector command)
   at MoBi.Engine.Sbml.SbmlTask.ImportModelFromSbml(String filename, IMoBiProject project)
   at MoBi.Presentation.Tasks.ProjectTask.OpenSBMLModel()
   at MoBi.Presentation.UICommand.ImportSbmlUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
[Zake2021_Metformin+Human+multiple+PO+dose.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/8771078/Zake2021_Metformin%2BHuman%2Bmultiple%2BPO%2Bdose.zip)

**Comment by StephanSchaller** [comment]
The SBML importer is a tricky thing due to the complexity of the Level3 SBML. Level2.4 should work most of the time and we have tested quite a few Level3 models.
@abdelr , correct me if I am wrong and could you look into this? Thanks

**Comment by abdelr** [comment]
The problem is on the mLiver Species when setting the molecule start values. It references the species which are defined further down in the sbml file. I moved the SpeciesList node up in the file and then it does not crash in the mLiver (which was the original place) but it crashes in the next species. So, all in all, because of the way the external SBML dll works, you cannot reference something that will be defined later in the file. This is in contradiction with the idea of having an xml file with nodes identified by their ids but it is how it works right now. There could be some ways to coupe with this from the code (lazy loading things) but I think it will be a big change. Also, to avoid the application to crash is not trivial. The error is a access violation exception. This is an exception we cannot safely catch. I actually discuss it with @msevestre today and maybe we would need to try to load the file on a safe process to see if it crashes and if not then load it into the main process. This will give you no information at all about the nature of the error though. So we will need to load the file twice just to avoid the application to crash but the error message will not be more informative than "there is something wrong with the file". 

> The SBML importer is a tricky thing due to the complexity of the Level3 SBML. Level2.4 should work most of the time and we have tested quite a few Level3 models. @abdelr , correct me if I am wrong and could you look into this? Thanks

@StephanSchaller: This problem with the order of nodes will be present even when we use no special features from deprecated versions (or levels) of SBML.

**Comment by Yuri05** [comment]
>maybe we would need to try to load the file on a safe process to see if it crashes and if not then load it into the main process. This will give you no information at all about the nature of the error though. So we will need to load the file twice just to avoid the application to crash but the error message will not be more informative than "there is something wrong with the file".

Before trying this: should we upgrade to the latest libSbml (5.19) first and check if it fixes the problem?
https://github.com/sbmlteam/libsbml/releases/latest

**Comment by abdelr** [comment]
Updating dll did not solve the issue :(. I would recommend some kind of lazy loading here. So if we have not yet loaded some species we should not try to use it until it is loaded. We need to keep a reference to the place where it was needed and then come back later when we have enough information to fill in the blanks. I am surprised the the lib does not support this already though.
