### ISSUE TITLE
Mobi 11 returned error while trying to create a new PKSIM molecule.

### ISSUE THREAD

**Issue by Sulav1** [Open-Systems-Pharmacology/MoBi#726]
when I try to create a new PKSIM molecule in a project using portable Mobi, I received following error.

-------------------------------------------------------------------------------------------------------------------------

Application:
MoBi® 11.0.138

Could not find a part of the path 'Placeholder\mobi-portable-setup\MoBi 11.0.138\Templates\Standard Molecule.pkml'.

Stack trace:
```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Presenter.CreatePKSimMoleculePresenter.loadMoleculeFromTemplate()
   at MoBi.Presentation.Presenter.CreatePKSimMoleculePresenter.CreateMolecule(IMoleculeBuildingBlock moleculeBuildingBlock)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForMoleculeBuilder.AddPKSimMoleculeTo(IMoleculeBuildingBlock moleculeBuildingBlock)
   at MoBi.Presentation.UICommand.AddPKSimMoleculeCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
oh this is with the portable version.. I see
