### ISSUE TITLE
Error when trying to clear history

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#758]
Hitting on the "Clear history" button in the "Utilities" tab:

Application:
MoBi® 11.0.138

SQL logic error
no such table: HISTORY_ITEMS

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at OSPSuite.Infrastructure.Serialization.Services.HistoryTask.clearCommand(DbConnection connection)
   at OSPSuite.Infrastructure.Serialization.Services.SQLiteProjectCommandExecuter.ExecuteCommand(String projectFile, Action`1 command)
   at OSPSuite.Infrastructure.Serialization.Services.HistoryTask.clearProjectHistory()
   at OSPSuite.Infrastructure.Serialization.Services.HistoryTask.ClearHistory()
   at OSPSuite.Presentation.UICommands.ClearHistoryUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Works.
