### ISSUE TITLE
Exception error after Reaction commit to building block

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#79]
1. Open ManualModel_Sim.mbp3
2. Open the Reactions BB, then add a +global+ parameter to reaction R1.
3. Update simulation S1 from Reactions BB, then open it. - These steps were all preparation to add a feature that will allow a "Commit" after change.
4. Change the value of the newly added global parameter in R1. Reaction will be flagged red in S1 configuration.
5. Commit Reaction to building block.
6. Open Reaction, then click on any reaction symbol in the chart (or switch to the list and click there).

The following exception is thrown, build 36 was used:

Application:
MoBi 7.1.0 - Build 36

Unable to cast object of type 'OSPSuite.UI.Diagram.Managers.ReactionDiagramManager`1[MoBi.Core.Domain.Model.IMoBiReactionBuildingBlock]' to type 'MoBi.Core.Domain.Model.Diagram.IMoBiReactionDiagramManager'.

Stack trace:
```
at OSPSuite.Utility.Extensions.ConversionExtensions.DowncastTo[T](Object objectToCast)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.get_reactionDiagramManager()
   at MoBi.UI.Presenters.ReactionDiagramPresenter.Select(IReactionBuilder reactionBuilder)
   at MoBi.Presentation.Presenter.EditReactionBuildingBlockPresenter.SelectBuilder(IReactionBuilder reactionBuilder)
   at MoBi.Presentation.Presenter.EditBuildingBlockPresenterBase`4.selectObjectAndParent(IObjectBase parentObject, IObjectBase selectedObject)
   at MoBi.Presentation.Presenter.EditBuildingBlockPresenterBase`4.Handle(EntitySelectedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_0`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by UlrichSi** [comment]
Ok now.
