### ISSUE TITLE
11. Crash when simulation doesn't have results

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#791]
[01.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/9981065/01.zip)
I exported the simulation S1 as pkml from PK-Sim and tried to import it in MoBi.
Then the exception below came. Simulation contains predicted vs observed and residul vs time plot

```
Application:

MoBi® 11.1.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Presentation.Presenters.Charts.ChartEditorPresenter.<>c.<AddDataRepositories>b__58_0(DataRepository x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Presenters.Charts.ChartEditorPresenter.AddDataRepositories(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.Charts.ChartPresenter`3.AddDataRepositoriesToEditor(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.SimulationVsObservedDataChartPresenter`1.AddResultRepositoryToEditor(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.SimulationPredictedVsObservedChartPresenter.addPredictedVsObservedToChart(DataRepository simulationResult, Action`2 action)
   at OSPSuite.Presentation.Presenters.SimulationPredictedVsObservedChartPresenter.AddRunResultToChart()
   at OSPSuite.Presentation.Presenters.SimulationVsObservedDataChartPresenter`1.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at MoBi.Presentation.Presenter.EditSimulationPresenter.loadChart() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\EditSimulationPresenter.cs:line 164
   at MoBi.Presentation.Presenter.EditSimulationPresenter.Edit(IMoBiSimulation simulation) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\EditSimulationPresenter.cs:line 138
   at MoBi.Presentation.Presenter.EditSimulationPresenter.Edit(Object subject) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Presenter\EditSimulationPresenter.cs:line 154
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.editEntiy(T entity) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\Edit\EditTasksForBuildingBlock.cs:line 39
   at MoBi.Presentation.Tasks.Edit.EditTasksForBuildingBlock`1.Edit(T buildingBlock) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\Edit\EditTasksForBuildingBlock.cs:line 28
   at MoBi.Presentation.Tasks.Edit.EditTasksForSimulation.Edit(IMoBiSimulation simulation) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\Tasks\Edit\EditTasksForSimulation.cs:line 83
   at MoBi.Presentation.UICommand.EditSimulationUICommand.PerformExecute() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Presentation\UICommand\EditSimulationUICommand.cs:line 18
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)

**Comment by Yuri05** [comment]
@msevestre @georgeDaskalakis @rwmcintosh Seems that even simulation without any new plots cannot be imported in MoBi anymore

**Comment by georgeDaskalakis** [comment]
@Yuri05 I am on it.

**Comment by msevestre** [comment]
@Yuri05 Seems to be unrelated to the predicted vs observed chart. It's not even exporter

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1773](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1773) via [**Zenhub**](https://www.zenhub.com/)
