### ISSUE TITLE
Extended PDF Report of simulation throws exception error

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#81]
1. Open the ManualModel
2. Right-click on simulation S1 (after tree expansion), select "Export to PDF".
3. In the window that opens, select "Extended output (descriptions, images etc)", then click "Create".
4. Leave the default filename, then click "Save".
The following error is thrown (build 36):

Application:
MoBi 7.1.0 - Build 36

One or more errors occurred.
-----------------------------------------------------
No component for supporting the service OSPSuite.Presentation.Presenters.Diagram.IBaseDiagramPresenter`1[[MoBi.Core.Domain.Model.IMoBiSimulation, MoBi.Core, Version=7.1.0.36, Culture=neutral, PublicKeyToken=null]] was found

Stack trace:
```
at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at OSPSuite.Presentation.Core.ApplicationController.Start[TPresenter]()
   at MoBi.Presentation.Tasks.DiagramModelToImageTask.CreateFor[T](T withDiagramModel)
   at MoBi.Presentation.Tasks.DiagramModelToImageTask.ExportTo[T](T withDiagramModel, String imageFilePath)
   at MoBi.Core.Reporting.SimulationReporter.Report(IMoBiSimulation simulation, OSPSuiteTracker buildTracker)
   at OSPSuite.Infrastructure.Reporting.OSPSuiteTeXReporter`1.Report(Object objectToReport, OSPSuiteTracker buildTracker)
   at OSPSuite.Infrastructure.Reporting.ReportingTask.<CreateReportAsync>d__6.MoveNext()
 --- End of inner exception stack trace ---
```

**Comment by UlrichSi** [comment]
Ok now.
