### ISSUE TITLE
Error loading the .pkml

### ISSUE THREAD

**Issue by t-anton** [Open-Systems-Pharmacology/MoBi#863]
Application:
MoBi® 11.0.138

Data at the root level is invalid. Line 1, position 1.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.ProjectTask.loadSimulationTransferFromFileUsingDimensionMode(String fileName, ReactionDimensionMode dimensionMode)
   at MoBi.Presentation.Tasks.ProjectTask.LoadSimulationTransferDataFromFile(String fileName)
   at MoBi.Presentation.Tasks.ProjectTask.<>c__DisplayClass15_0.<loadSimulationFromFileInProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Yuri05** [comment]
You have downloaded the html page. To download the pkml, click on **Raw** or on **Download** button
